const recommendationEngine = createRecommendationEngine({ todayKey });

const calendarService={provider:'apple',mode:'backend-required',capabilities:{readEvents:true,writeEvents:true,multipleCalendars:true,eventKitReady:true},status:async()=>({connected:false,calendars:[],lastSync:null}),connect:async()=>{throw new Error('SECURE_BACKEND_REQUIRED')},sync:async()=>[],disconnect:async()=>true,createEvent:async()=>{throw new Error('SECURE_BACKEND_REQUIRED')}};
document.addEventListener('click',e=>{if(e.target.closest('.task-row,.suggestion-card')&&!e.target.closest('.check,.more-button,.swap-button'))detailOrigin=currentScreen},true);
const $=id=>document.getElementById(id), clone=v=>JSON.parse(JSON.stringify(v));
const migrateImportance=i=>numericOrNull(i.importance)??({1:4,2:3,3:2,4:1,5:1}[Number(i.priority)]??null);
let actions=read(KEYS.actions).map((i,n)=>({id:i.id||uid(),title:i.title||i.text||'',importance:migrateImportance(i),necessity:numericOrNull(i.necessity),impact:numericOrNull(i.impact),resistance:numericOrNull(i.resistance),load:numericOrNull(i.load),resistanceReason:i.resistanceReason||'',resistanceReasons:Array.isArray(i.resistanceReasons)?i.resistanceReasons:(i.resistanceReason?[i.resistanceReason]:[]),duration:i.duration==null?null:Number(i.duration),durationExplicit:!!i.durationExplicit,projectId:i.projectId||'',note:i.note||'',deadline:i.deadline||{enabled:false,date:''},repeat:i.repeat||{enabled:false,every:1,unit:'weeks',lastDone:'',nextDue:''},blocker:i.blocker||{enabled:false,text:'',availableFrom:''},lifecycle:i.lifecycle||{state:i.done?'completed':i.blocker?.enabled?'waiting':'open',deferredUntil:''},done:!!i.done,postponeCount:Number(i.postponeCount)||0,completionCount:Number(i.completionCount)||0,rejectedOn:i.rejectedOn||'',recommendationHistory:i.recommendationHistory||{lastRecommended:'',count:0,skips:[]},completionHistory:Array.isArray(i.completionHistory)?i.completionHistory:[],inference:i.inference||{source:'user',confidence:null},type:i.type||'task',order:Number.isFinite(Number(i.order))?Number(i.order):n,createdAt:i.createdAt||Date.now()+n}));
const colors=['purple','pink','blue','teal','green','gold','rose','indigo'];
const displayProjectName=value=>{const text=String(value||'').trim();return text?text.charAt(0).toLocaleUpperCase('nl-NL')+text.slice(1).toLocaleLowerCase('nl-NL'):''};
let projects=read(KEYS.projects).map((p,n)=>({id:p.id||uid(),title:p.title||'Project',color:p.color||colors[n%8],archived:!!p.archived,deadline:p.deadline||'',order:Number.isFinite(Number(p.order))?Number(p.order):n,createdAt:p.createdAt||Date.now()}));
let wishlist=read(KEYS.wishlist).map((w,n)=>{const item={...w,id:w.id||uid(),name:w.name||'',price:w.price===''?'':Number(w.price),hasPrice:w.hasPrice??(w.price!==''&&w.price!=null),note:w.note||'',link:w.link||'',photo:w.photo||'',color:w.color||'',bought:!!w.bought,order:Number.isFinite(Number(w.order))?Number(w.order):n,createdAt:w.createdAt||Date.now()};if(['need','wish'].includes(w.purchaseType))item.purchaseType=w.purchaseType;else delete item.purchaseType;if(Number(w.importance))item.importance=Number(w.importance);else delete item.importance;if(w.deadline?.enabled&&w.deadline?.date)item.deadline={enabled:true,date:w.deadline.date};else if(w.dueDate)item.deadline={enabled:true,date:w.dueDate};else delete item.deadline;return item});
let bucketlist=read(KEYS.bucketlist,null);if(!bucketlist)bucketlist=[{id:uid(),name:'2026',items:[]},{id:uid(),name:'Ooit',items:[]},{id:uid(),name:'Eten & proberen',items:[]}];
let lists=read(KEYS.lists),ideas=read(KEYS.ideas).map((i,n)=>typeof i==='string'?{id:uid(),text:i,order:n}:{...i,id:i.id||uid(),order:Number.isFinite(Number(i.order))?Number(i.order):n}),inbox=read(KEYS.inbox).map((i,n)=>typeof i==='string'?{id:uid(),text:i,order:n,createdAt:Date.now()+n}:{...i,id:i.id||uid(),text:i.text||'',order:Number.isFinite(Number(i.order))?Number(i.order):n,createdAt:i.createdAt||Date.now()+n});
let financeItems=read(KEYS.finance).map((item,n)=>({...item,id:item.id||uid(),title:item.title||'',amount:Number(item.amount)||0,paid:Number(item.paid)||0,direction:item.direction==='pay'?'pay':'receive',party:item.party||'',date:item.date||'',dueDate:item.dueDate||'',status:['open','partial','done'].includes(item.status)?item.status:'open',note:item.note||'',order:Number.isFinite(+item.order)?+item.order:n,createdAt:item.createdAt||Date.now()+n}));
let documents=read(KEYS.documents).map((item,n)=>({...item,id:item.id||uid(),title:item.title||'',fileName:item.fileName||'',fileData:item.fileData||'',fileType:item.fileType||'',category:item.category||'',date:item.date||'',party:item.party||'',amount:item.amount===''?'':Number(item.amount)||'',note:item.note||'',tags:Array.isArray(item.tags)?item.tags:[],order:Number.isFinite(+item.order)?+item.order:n,createdAt:item.createdAt||Date.now()+n}));
const SETTINGS_DEFAULTS={suggestionMode:'few',guidance:'balanced',taskReminders:false,dailyCheckin:false,reducedMotion:false};
let appSettings={...SETTINGS_DEFAULTS,...read(KEYS.settings,{})};
let energy=Number(read(KEYS.energy,null))||null,checkin=read(KEYS.checkin,{date:'',energy:null,updatedAt:null}),feedbackDraft=read(KEYS.feedback,{type:'',text:'',updatedAt:null}),currentScreen='home',previousScreen='home',detailOrigin='home',currentProjectId=null,currentListId=null,currentSublist='main',masterFilter='open',wishlistFilter='open',purchaseFilter='all',editingActionId=null,editingProjectId=null,editingWishlistId=null,editingListId=null,editingIdeaId=null,editingSublistName=null,selectedSublistColor='',selectedListColor='',selectedWishlistColor='',selectedPurchaseType='',purchaseImportance=null,formImportance=null,formImpact=null,formResistance=null,formLoad=null,selectedResistanceReasons=[],activeActionExtras=new Set(),selectedColor='purple',selectedListType='list',undo=null,drag=null,pendingDeleteAction=null,pendingInboxConversionId=null,homeSwappedIds=new Set();
const saveBucketlist=()=>write(KEYS.bucketlist,bucketlist);
const saveActions=()=>write(KEYS.actions,actions),saveProjects=()=>write(KEYS.projects,projects),saveWishlist=()=>write(KEYS.wishlist,wishlist),saveLists=()=>write(KEYS.lists,lists),saveIdeas=()=>write(KEYS.ideas,ideas),saveInbox=()=>write(KEYS.inbox,inbox),saveFinance=()=>write(KEYS.finance,financeItems),saveDocuments=()=>write(KEYS.documents,documents);
let purchaseSort='manual';
let actionFormInitial='';
function actionFormState(){return JSON.stringify({title:$('actionTitle').value,importance:formImportance,resistance:formResistance,reasons:selectedResistanceReasons,duration:activeActionExtras.has('duration')?$('duration').value:'',deadline:$('deadlineDate').value,project:$('actionProject').value,repeat:activeActionExtras.has('repeat')?[$('repeatEvery').value,$('repeatUnit').value,$('lastDone').value]:null,note:$('actionNote').value})}
saveActions();saveProjects();saveWishlist();saveIdeas();
const wishlistColorField=document.createElement('div');wishlistColorField.className='wishlist-color-field';wishlistColorField.innerHTML='<label class="small-label">Kleur (optioneel)</label><div class="color-picker"><button class="color-choice none selected" data-wishlist-color=""></button><button class="color-choice purple" data-wishlist-color="purple"></button><button class="color-choice pink" data-wishlist-color="pink"></button><button class="color-choice blue" data-wishlist-color="blue"></button><button class="color-choice teal" data-wishlist-color="teal"></button><button class="color-choice green" data-wishlist-color="green"></button><button class="color-choice gold" data-wishlist-color="gold"></button><button class="color-choice rose" data-wishlist-color="rose"></button></div>';$('saveWishlistButton').before(wishlistColorField);document.querySelectorAll('[data-wishlist-color]').forEach(b=>b.onclick=()=>{selectedWishlistColor=b.dataset.wishlistColor;document.querySelectorAll('[data-wishlist-color]').forEach(x=>x.classList.toggle('selected',x===b))});

function syncGlobalAdd(){const blocked=['capture','listDetail','inbox'].includes(currentScreen)||document.querySelector('.overlay:not(.hidden),.menu-overlay:not(.hidden)');$('globalAddButton').classList.toggle('hidden',!!blocked)}
function showScreen(name){previousScreen=currentScreen;currentScreen=name;document.querySelectorAll('.screen').forEach(s=>s.classList.toggle('active',s.id===name+'Screen'));document.querySelectorAll('.nav-button').forEach(b=>b.classList.toggle('active',b.dataset.screen===name));if(name==='home')renderHome();if(name==='masterlist')renderMasterlist();if(name==='wishlist')renderWishlist();if(name==='projects')renderProjects();if(name==='lists')renderLists();if(name==='ideas')renderIdeas();if(name==='bucketlist')renderBucketlist();if(name==='chores')renderChores();if(name==='inbox')renderInbox();if(name==='finance')renderFinance();if(name==='documents')renderDocuments();if(name==='settings')renderSettings();syncGlobalAdd();window.scrollTo(0,0)}
document.querySelectorAll('.nav-button').forEach(b=>b.onclick=()=>{if(currentScreen==='capture')pendingInboxConversionId=null;showScreen(b.dataset.screen)});
document.querySelectorAll('.vault-back').forEach(b=>b.onclick=()=>showScreen('vault'));
$('seeProjectsButton').onclick=() => showScreen('projects');$('masterlistModule').onclick=()=>showScreen('masterlist');$('masterlistBackButton').onclick=()=>showScreen('vault');$('wishlistModule').onclick=()=>showScreen('wishlist');$('listsModule').onclick=()=>showScreen('lists');$('ideasModule').onclick=()=>showScreen('ideas');$('bucketlistModule').onclick=()=>showScreen('bucketlist');$('choresModule').onclick=()=>showScreen('chores');
if($('vaultVisualSearch'))$('vaultVisualSearch').oninput=()=>{const q=$('vaultVisualSearch').value.trim().toLowerCase();document.querySelectorAll('#vaultScreen .module-card').forEach(card=>card.classList.toggle('vault-search-hidden',!!q&&!card.textContent.toLowerCase().includes(q)))};

// Intelligence notes: object type never implies importance or urgency. Importance and deadline are independent signals; a deadline only reduces how long waiting remains possible. A wish may matter, a needed purchase may wait, and current energy belongs to user context rather than any object. Only collect context that can later be used deliberately.
