const LUMI_TRANSLATIONS={
  nl:{
    'task.load':'Belasting','task.impact':'Opbrengst','task.necessity':'Noodzaak','task.deleteConfirm':'Weet je zeker dat je deze taak wilt verwijderen?','level.low':'Weinig','level.medium':'Redelijk','level.high':'Veel','level.veryHigh':'Heel veel','necessity.wait':'Kan rustig wachten','necessity.drawback':'Uitstel geeft nadelen','necessity.must':'Moet echt gebeuren','necessity.problem':'Uitstel veroorzaakt problemen',
    'status.open':'Open','status.waiting':'Wachten op','status.later':'Later','status.done':'Gedaan',
    'waiting.forPrompt':'Waar/wie wacht je op? (optioneel)','waiting.followUpPrompt':'Wanneer wil je dit weer zien? Vul een datum in als JJJJ-MM-DD, of laat leeg.','waiting.since':'Wacht sinds {date}','waiting.noResponse':'Nog geen reactie van {name}','waiting.generic':'Wachten op opvolging','waiting.keep':'Nog wachten','waiting.followUp':'Opvolgen','waiting.set':'Wachten op',
    'later.set':'Later','later.prompt':'Wanneer wil je dit weer zien? Vul een datum in als JJJJ-MM-DD, of laat leeg voor geen datum.','later.noDate':'Geen datum','later.resurfaced':'Teruggebracht','later.resurface':'Terugbrengen',
    'date.planned':'Gepland','date.deadline':'Deadline','date.resurface':'Terugbrengen','date.invalid':'Gebruik een geldige datum in de vorm JJJJ-MM-DD.',
    'recurrence.afterCompletion':'Na voltooiing','recurrence.daily':'Dagelijks','recurrence.weekly':'Wekelijks','recurrence.monthly':'Maandelijks','recurrence.quarterly':'Per kwartaal','recurrence.halfYearly':'Halfjaarlijks','recurrence.yearly':'Jaarlijks','recurrence.every':'Iedere {interval} {unit}','recurrence.day.one':'dag','recurrence.day.many':'dagen','recurrence.week.one':'week','recurrence.week.many':'weken','recurrence.month.one':'maand','recurrence.month.many':'maanden','recurrence.year.one':'jaar','recurrence.year.many':'jaar',
    'reason.energyFit':'Past bij je energie','reason.lowEnergy':'Weinig energie','reason.deadline':'Deadline nadert','reason.important':'Binnenkort belangrijk','reason.lowResistance':'Weinig weerstand','reason.resurfaced':'Opnieuw relevant','reason.duration':'± {minutes} min',
    'menu.edit':'Bewerken','menu.delete':'Verwijderen','menu.cancel':'Annuleren'
    ,'capture.saveNow':'Nu bewaren','capture.addContext':'Context toevoegen','capture.saveTask':'Bewaar in mijn Vault','context.title':'Extra context','context.help':'Alles hieronder is optioneel.','task.energyQuestion':'Hoeveel vraagt het van je als je ermee bezig bent?','task.resistanceQuestion':'Hoeveel weerstand voel je?','task.impactQuestion':'Wat levert het op als het gedaan is?','impact.low':'Weinig','impact.some':'Een beetje','impact.much':'Veel','impact.veryMuch':'Heel veel','resurface.question':'Wanneer wil je hier weer aan denken?'
    ,'purchase.typeQuestion':'Heb je het nodig of is het een wens?','purchase.timingQuestion':'Wanneer heb je het nodig / kan het wachten?','purchase.extraTitle':'Extra informatie','purchase.price':'Prijs','purchase.addPrice':'Voeg een prijs toe','purchase.link':'Link','purchase.addLink':'Voeg een link toe','purchase.photo':'Foto','purchase.addPhoto':'Voeg een foto toe','purchase.date':'Voor een bepaalde datum','purchase.addDate':'Voeg datum toe','purchase.color':'Kleur (optioneel)'
    ,'purchase.need':'Nodig','purchase.wish':'Wens','purchase.wishlist':'Wishlist','purchase.canWait':'Kan wachten','purchase.soon':'Binnenkort','purchase.now':'Nu nodig','purchase.emptyDone':'Nog niets gekocht','purchase.emptyNeed':'Nog niets nodig','purchase.emptyWish':'Nog geen wensen','purchase.empty':'Nog geen aankopen','purchase.edit':'Aankoop bewerken','purchase.new':'Nieuwe aankoop','purchase.photoKept':'Foto bewaard','purchase.wishTiming':'Wanneer zou je dit willen?','purchase.needTiming':'Wanneer heb je dit nodig?','purchase.noRush':'Geen haast','purchase.byDate':'Voor een datum'
    ,'project.edit':'Project bewerken','project.new':'Nieuw project'
    ,'bucket.defaults.2026':'2026','bucket.defaults.2027':'2027','bucket.defaults.someday':'Ooit','bucket.empty':'Nog niets toegevoegd.','bucket.addItem':'+ Item toevoegen','bucket.addList':'+ Lijst toevoegen','bucket.listName':'Naam van de nieuwe bucketlist','bucket.rename':'Hernoemen','bucket.color':'Kleur kiezen','bucket.delete':'Verwijderen','bucket.itemPrompt':'Toevoegen aan {name}','bucket.itemEdit':'Bucketlist-item'
    ,'energy.eyebrow':'Jouw energie','energy.question':'Hoeveel ruimte heb je nu?','energy.help':'Kies wat het dichtst in de buurt komt.','energy.homeQuestion':'Hoe is je energie?','energy.homeHelp':'Geef aan hoeveel ruimte je hebt.','energy.currentTitle':'Jouw energie','energy.notSet':'Nog niet ingevuld','energy.set':'Energie aangeven','energy.change':'Energie wijzigen','energy.settingsCurrent':'Huidige energie: niveau {level}','energy.settingsHelp':'Bekijk en pas je energie aan','energy.level.1':'Heel weinig','energy.level.2':'Weinig','energy.level.3':'Redelijk','energy.level.4':'Best veel','energy.level.5':'Veel','energy.status.1':'Heel weinig energie','energy.status.2':'Weinig energie','energy.status.3':'Redelijke energie','energy.status.4':'Best veel energie','energy.status.5':'Veel energie'
    ,'today.viewTask':'{title} bekijken','today.swap':'Wissel taak','today.noAlternative':'Ik zie op dit moment geen andere taak die goed bij je past.','today.swapped':'Geen probleem. Ik heb een andere suggestie voor je.','today.broadened':'Je ziet nu bewust ook opties die wat meer kunnen vragen.','today.broaden':'Ook zwaardere opties bekijken','today.broadenHelp':'Ook taken bekijken die wat meer van je vragen.','today.orderSaved':'Volgorde bewaard.','today.emptyTitle':'Geen passende taken voor nu','today.emptyHelp':'Je hoeft nu niets te forceren.','energy.save':'Energie bewaren'
    ,'task.completed':'Afgerond ✓','undo':'Ongedaan maken','masterlist.noResults':'Geen taken gevonden','masterlist.adjustSearch':'Pas je zoekopdracht aan','masterlist.emptyDone':'Nog niets afgerond','masterlist.emptyDoneHelp':'Afgeronde taken verschijnen hier','masterlist.emptyWaiting':'Niets staat te wachten','masterlist.emptyWaitingHelp':'Taken die van iets of iemand anders afhangen verschijnen hier','masterlist.emptyLater':'Niets voor later','masterlist.emptyLaterHelp':'Uitgestelde taken verschijnen hier','masterlist.emptyOpen':'Nog geen taken','masterlist.emptyOpenHelp':'Voeg een taak toe'
    ,'capture.closeConfirm':'Wil je de capture sluiten? Je invoer blijft als concept bewaard.','capture.close':'Sluiten','capture.saveChanges':'Wijzigingen opslaan','capture.deleteDraftConfirm':'Wil je dit concept verwijderen?','capture.deleteDraft':'Concept verwijderen'
    ,'color.purple':'Paars','color.pink':'Roze','color.blue':'Blauw','color.teal':'Turquoise','color.green':'Groen','color.gold':'Goud','color.rose':'Rood'
  },
  en:{
    'task.load':'Demand','task.impact':'Benefit','task.necessity':'Necessity','task.deleteConfirm':'Are you sure you want to delete this task?','level.low':'Low','level.medium':'Moderate','level.high':'High','level.veryHigh':'Very high','necessity.wait':'Can wait','necessity.drawback':'Delay has drawbacks','necessity.must':'Must be done','necessity.problem':'Delay causes problems',
    'status.open':'Open','status.waiting':'Waiting for','status.later':'Later','status.done':'Done',
    'waiting.forPrompt':'Who or what are you waiting for? (optional)','waiting.followUpPrompt':'When should this return? Enter YYYY-MM-DD or leave blank.','waiting.since':'Waiting since {date}','waiting.noResponse':'No response from {name} yet','waiting.generic':'Waiting for follow-up','waiting.keep':'Keep waiting','waiting.followUp':'Follow up','waiting.set':'Waiting for',
    'later.set':'Later','later.prompt':'When should this return? Enter YYYY-MM-DD or leave blank for no date.','later.noDate':'No date','later.resurfaced':'Resurfaced','later.resurface':'Resurface',
    'date.planned':'Planned','date.deadline':'Deadline','date.resurface':'Resurface','date.invalid':'Use a valid date in the form YYYY-MM-DD.',
    'recurrence.afterCompletion':'After completion','recurrence.daily':'Daily','recurrence.weekly':'Weekly','recurrence.monthly':'Monthly','recurrence.quarterly':'Quarterly','recurrence.halfYearly':'Every six months','recurrence.yearly':'Yearly','recurrence.every':'Every {interval} {unit}','recurrence.day.one':'day','recurrence.day.many':'days','recurrence.week.one':'week','recurrence.week.many':'weeks','recurrence.month.one':'month','recurrence.month.many':'months','recurrence.year.one':'year','recurrence.year.many':'years',
    'reason.energyFit':'Fits your energy','reason.lowEnergy':'Low energy','reason.deadline':'Deadline approaching','reason.important':'Important soon','reason.lowResistance':'Low resistance','reason.resurfaced':'Relevant again','reason.duration':'± {minutes} min',
    'menu.edit':'Edit','menu.delete':'Delete','menu.cancel':'Cancel'
    ,'capture.saveNow':'Save now','capture.addContext':'Add context','capture.saveTask':'Save in my Vault','context.title':'Extra context','context.help':'Everything below is optional.','task.energyQuestion':'How much energy does this take while you are doing it?','task.resistanceQuestion':'How much resistance do you feel?','task.impactQuestion':'What will it give you when it is done?','impact.low':'A little','impact.some':'Some','impact.much':'A lot','impact.veryMuch':'A great deal','resurface.question':'When do you want to think about this again?'
    ,'purchase.typeQuestion':'Do you need it or is it a wish?','purchase.timingQuestion':'When do you need it / can it wait?','purchase.extraTitle':'Extra information','purchase.price':'Price','purchase.addPrice':'Add a price','purchase.link':'Link','purchase.addLink':'Add a link','purchase.photo':'Photo','purchase.addPhoto':'Add a photo','purchase.date':'Before a certain date','purchase.addDate':'Add a date','purchase.color':'Color (optional)'
    ,'purchase.need':'Need','purchase.wish':'Wish','purchase.wishlist':'Wishlist','purchase.canWait':'Can wait','purchase.soon':'Soon','purchase.now':'Need now','purchase.emptyDone':'Nothing purchased yet','purchase.emptyNeed':'Nothing needed yet','purchase.emptyWish':'No wishes yet','purchase.empty':'No purchases yet','purchase.edit':'Edit purchase','purchase.new':'New purchase','purchase.photoKept':'Photo saved','purchase.wishTiming':'When would you like this?','purchase.needTiming':'When do you need this?','purchase.noRush':'No rush','purchase.byDate':'By a date'
    ,'project.edit':'Edit project','project.new':'New project'
    ,'bucket.defaults.2026':'2026','bucket.defaults.2027':'2027','bucket.defaults.someday':'Someday','bucket.empty':'Nothing added yet.','bucket.addItem':'+ Add item','bucket.addList':'+ Add list','bucket.listName':'Name of the new bucket list','bucket.rename':'Rename','bucket.color':'Choose color','bucket.delete':'Delete','bucket.itemPrompt':'Add to {name}','bucket.itemEdit':'Bucket list item'
    ,'energy.eyebrow':'Your energy','energy.question':'How much capacity do you have right now?','energy.help':'Choose what comes closest.','energy.homeQuestion':'How is your energy?','energy.homeHelp':'Indicate how much capacity you have.','energy.currentTitle':'Your energy','energy.notSet':'Not set yet','energy.set':'Set energy','energy.change':'Change energy','energy.settingsCurrent':'Current energy: level {level}','energy.settingsHelp':'View and change your energy','energy.level.1':'Very little','energy.level.2':'Low','energy.level.3':'Moderate','energy.level.4':'Quite a lot','energy.level.5':'High','energy.status.1':'Very little energy','energy.status.2':'Low energy','energy.status.3':'Moderate energy','energy.status.4':'Quite a lot of energy','energy.status.5':'High energy'
    ,'today.viewTask':'View {title}','today.swap':'Swap task','today.noAlternative':'I cannot find another task that fits right now.','today.swapped':'No problem. I found another suggestion.','today.broadened':'You are now also seeing options that may take more energy.','today.broaden':'Also show heavier options','today.broadenHelp':'Also show tasks that may take more energy.','today.orderSaved':'Order saved.','today.emptyTitle':'No suitable tasks right now','today.emptyHelp':'You do not need to force anything right now.','energy.save':'Save energy'
    ,'task.completed':'Completed ✓','undo':'Undo','masterlist.noResults':'No tasks found','masterlist.adjustSearch':'Adjust your search','masterlist.emptyDone':'Nothing completed yet','masterlist.emptyDoneHelp':'Completed tasks appear here','masterlist.emptyWaiting':'Nothing is waiting','masterlist.emptyWaitingHelp':'Tasks that depend on someone or something appear here','masterlist.emptyLater':'Nothing for later','masterlist.emptyLaterHelp':'Deferred tasks appear here','masterlist.emptyOpen':'No tasks yet','masterlist.emptyOpenHelp':'Add a task'
    ,'capture.closeConfirm':'Close capture? Your input remains saved as a draft.','capture.close':'Close','capture.saveChanges':'Save changes','capture.deleteDraftConfirm':'Delete this draft?','capture.deleteDraft':'Delete draft'
    ,'color.purple':'Purple','color.pink':'Pink','color.blue':'Blue','color.teal':'Teal','color.green':'Green','color.gold':'Gold','color.rose':'Red'
  }
};
function lumiLocale(){const code=(document.documentElement.lang||navigator.language||'nl').toLowerCase();return code.startsWith('en')?'en':'nl'}
function t(key,values={}){const locale=lumiLocale(),template=LUMI_TRANSLATIONS[locale][key]??LUMI_TRANSLATIONS.nl[key]??key;return template.replace(/\{(\w+)\}/g,(_,name)=>values[name]??'')}
function applyI18n(root=document){root.querySelectorAll('[data-i18n]').forEach(node=>{node.textContent=t(node.dataset.i18n)})}
