const LUMI_TRANSLATIONS={
  nl:{
    'status.open':'Open','status.waiting':'Wachten op','status.later':'Later','status.done':'Gedaan',
    'waiting.forPrompt':'Waar/wie wacht je op? (optioneel)','waiting.followUpPrompt':'Wanneer wil je dit weer zien? Vul een datum in als JJJJ-MM-DD, of laat leeg.','waiting.since':'Wacht sinds {date}','waiting.noResponse':'Nog geen reactie van {name}','waiting.generic':'Wachten op opvolging','waiting.keep':'Nog wachten','waiting.followUp':'Opvolgen','waiting.set':'Wachten op',
    'later.set':'Later','later.prompt':'Wanneer wil je dit weer zien? Vul een datum in als JJJJ-MM-DD, of laat leeg voor geen datum.','later.noDate':'Geen datum','later.resurfaced':'Teruggebracht','later.resurface':'Terugbrengen',
    'date.planned':'Gepland','date.deadline':'Deadline','date.resurface':'Terugbrengen','date.invalid':'Gebruik een geldige datum in de vorm JJJJ-MM-DD.',
    'recurrence.afterCompletion':'Na voltooiing','recurrence.daily':'Dagelijks','recurrence.weekly':'Wekelijks','recurrence.monthly':'Maandelijks','recurrence.quarterly':'Per kwartaal','recurrence.halfYearly':'Halfjaarlijks','recurrence.yearly':'Jaarlijks','recurrence.every':'Iedere {interval} {unit}','recurrence.day.one':'dag','recurrence.day.many':'dagen','recurrence.week.one':'week','recurrence.week.many':'weken','recurrence.month.one':'maand','recurrence.month.many':'maanden','recurrence.year.one':'jaar','recurrence.year.many':'jaar',
    'reason.energyFit':'Past bij je energie','reason.lowEnergy':'Weinig energie','reason.deadline':'Deadline nadert','reason.important':'Binnenkort belangrijk','reason.lowResistance':'Weinig weerstand','reason.resurfaced':'Opnieuw relevant','reason.duration':'± {minutes} min',
    'menu.edit':'Bewerken','menu.delete':'Verwijderen','menu.cancel':'Annuleren'
    ,'capture.saveNow':'Nu bewaren','capture.addContext':'Context toevoegen','capture.saveTask':'Bewaar in mijn Vault','context.title':'Extra context','context.help':'Alles hieronder is optioneel.','task.energyQuestion':'Hoeveel vraagt het van je als je ermee bezig bent?','task.resistanceQuestion':'Hoeveel weerstand voel je?','task.impactQuestion':'Wat levert het op als het gedaan is?','impact.low':'Weinig','impact.some':'Een beetje','impact.much':'Veel','impact.veryMuch':'Heel veel','resurface.question':'Wanneer wil je hier weer aan denken?'
    ,'purchase.typeQuestion':'Heb je het nodig of is het een wens?','purchase.timingQuestion':'Wanneer heb je het nodig / kan het wachten?','purchase.extraTitle':'Extra informatie','purchase.price':'Prijs','purchase.addPrice':'Voeg een prijs toe','purchase.link':'Link','purchase.addLink':'Voeg een link toe','purchase.photo':'Foto','purchase.addPhoto':'Voeg een foto toe','purchase.date':'Voor een bepaalde datum','purchase.addDate':'Voeg datum toe','purchase.color':'Kleur (optioneel)'
    ,'purchase.need':'Nodig','purchase.wish':'Wens','purchase.canWait':'Kan wachten','purchase.soon':'Binnenkort','purchase.now':'Nu nodig'
    ,'bucket.defaults.2026':'2026','bucket.defaults.2027':'2027','bucket.defaults.someday':'Ooit','bucket.empty':'Nog niets toegevoegd.','bucket.addItem':'+ Item toevoegen','bucket.addList':'+ Lijst toevoegen','bucket.listName':'Naam van de nieuwe bucketlist','bucket.rename':'Hernoemen','bucket.color':'Kleur kiezen','bucket.delete':'Verwijderen','bucket.itemPrompt':'Toevoegen aan {name}','bucket.itemEdit':'Bucketlist-item'
    ,'color.purple':'Paars','color.pink':'Roze','color.blue':'Blauw','color.teal':'Turquoise','color.green':'Groen','color.gold':'Goud','color.rose':'Rood'
  },
  en:{
    'status.open':'Open','status.waiting':'Waiting for','status.later':'Later','status.done':'Done',
    'waiting.forPrompt':'Who or what are you waiting for? (optional)','waiting.followUpPrompt':'When should this return? Enter YYYY-MM-DD or leave blank.','waiting.since':'Waiting since {date}','waiting.noResponse':'No response from {name} yet','waiting.generic':'Waiting for follow-up','waiting.keep':'Keep waiting','waiting.followUp':'Follow up','waiting.set':'Waiting for',
    'later.set':'Later','later.prompt':'When should this return? Enter YYYY-MM-DD or leave blank for no date.','later.noDate':'No date','later.resurfaced':'Resurfaced','later.resurface':'Resurface',
    'date.planned':'Planned','date.deadline':'Deadline','date.resurface':'Resurface','date.invalid':'Use a valid date in the form YYYY-MM-DD.',
    'recurrence.afterCompletion':'After completion','recurrence.daily':'Daily','recurrence.weekly':'Weekly','recurrence.monthly':'Monthly','recurrence.quarterly':'Quarterly','recurrence.halfYearly':'Every six months','recurrence.yearly':'Yearly','recurrence.every':'Every {interval} {unit}','recurrence.day.one':'day','recurrence.day.many':'days','recurrence.week.one':'week','recurrence.week.many':'weeks','recurrence.month.one':'month','recurrence.month.many':'months','recurrence.year.one':'year','recurrence.year.many':'years',
    'reason.energyFit':'Fits your energy','reason.lowEnergy':'Low energy','reason.deadline':'Deadline approaching','reason.important':'Important soon','reason.lowResistance':'Low resistance','reason.resurfaced':'Relevant again','reason.duration':'± {minutes} min',
    'menu.edit':'Edit','menu.delete':'Delete','menu.cancel':'Cancel'
    ,'capture.saveNow':'Save now','capture.addContext':'Add context','capture.saveTask':'Save in my Vault','context.title':'Extra context','context.help':'Everything below is optional.','task.energyQuestion':'How much energy does this take while you are doing it?','task.resistanceQuestion':'How much resistance do you feel?','task.impactQuestion':'What will it give you when it is done?','impact.low':'A little','impact.some':'Some','impact.much':'A lot','impact.veryMuch':'A great deal','resurface.question':'When do you want to think about this again?'
    ,'purchase.typeQuestion':'Do you need it or is it a wish?','purchase.timingQuestion':'When do you need it / can it wait?','purchase.extraTitle':'Extra information','purchase.price':'Price','purchase.addPrice':'Add a price','purchase.link':'Link','purchase.addLink':'Add a link','purchase.photo':'Photo','purchase.addPhoto':'Add a photo','purchase.date':'Before a certain date','purchase.addDate':'Add a date','purchase.color':'Color (optional)'
    ,'purchase.need':'Need','purchase.wish':'Wish','purchase.canWait':'Can wait','purchase.soon':'Soon','purchase.now':'Need now'
    ,'bucket.defaults.2026':'2026','bucket.defaults.2027':'2027','bucket.defaults.someday':'Someday','bucket.empty':'Nothing added yet.','bucket.addItem':'+ Add item','bucket.addList':'+ Add list','bucket.listName':'Name of the new bucket list','bucket.rename':'Rename','bucket.color':'Choose color','bucket.delete':'Delete','bucket.itemPrompt':'Add to {name}','bucket.itemEdit':'Bucket list item'
    ,'color.purple':'Purple','color.pink':'Pink','color.blue':'Blue','color.teal':'Teal','color.green':'Green','color.gold':'Gold','color.rose':'Red'
  }
};
function lumiLocale(){const code=(document.documentElement.lang||navigator.language||'nl').toLowerCase();return code.startsWith('en')?'en':'nl'}
function t(key,values={}){const locale=lumiLocale(),template=LUMI_TRANSLATIONS[locale][key]??LUMI_TRANSLATIONS.nl[key]??key;return template.replace(/\{(\w+)\}/g,(_,name)=>values[name]??'')}
function applyI18n(root=document){root.querySelectorAll('[data-i18n]').forEach(node=>{node.textContent=t(node.dataset.i18n)})}
