function wireDrag(el,scope,handle=el){let startX=0,startY=0,targetId='',active=false,justDragged=false;el.classList.add('draggable-item');const blocked=e=>e.target.closest('.check,.more-button,.column-menu,input,a');const begin=e=>{if(blocked(e))return false;startX=e.clientX;startY=e.clientY;targetId='';active=false;return true};const move=e=>{if(!active&&Math.hypot(e.clientX-startX,e.clientY-startY)>7){active=true;drag={id:el.dataset.id,scope};el.classList.add('dragging');navigator.vibrate?.(18)}if(!active)return;e.preventDefault();const target=document.elementFromPoint(e.clientX,e.clientY)?.closest('[data-id]');if(target?.dataset.id&&target.dataset.id!==el.dataset.id)targetId=target.dataset.id};const end=()=>{if(active){justDragged=true;if(targetId)reorder(scope,el.dataset.id,targetId);setTimeout(()=>justDragged=false,0)}active=false;drag=null;targetId='';el.classList.remove('dragging')};el.addEventListener('click',e=>{if(justDragged){e.preventDefault();e.stopImmediatePropagation()}},true);handle.onpointerdown=e=>{if(e.pointerType==='mouse'||!begin(e))return;handle.setPointerCapture?.(e.pointerId)};handle.onpointermove=e=>{if(e.pointerType==='mouse')return;move(e)};handle.onpointerup=e=>{if(e.pointerType==='mouse')return;end();handle.releasePointerCapture?.(e.pointerId)};handle.onpointercancel=end;handle.onmousedown=e=>{if(!begin(e))return;const mouseMove=event=>move(event),mouseUp=()=>{document.removeEventListener('mousemove',mouseMove);document.removeEventListener('mouseup',mouseUp);end()};document.addEventListener('mousemove',mouseMove);document.addEventListener('mouseup',mouseUp)}}
function reorderItems(arr,from,to,onMove){const a=arr.findIndex(x=>x.id===from),b=arr.findIndex(x=>x.id===to);if(a<0||b<0||a===b)return false;const target=arr[b],[m]=arr.splice(a,1);onMove?.(m,target);arr.splice(Math.min(b,arr.length),0,m);arr.forEach((x,n)=>x.order=n);return true}
function reorder(scope,from,to){if(scope==='today'){const visible=suggestions(),fromIndex=visible.findIndex(item=>item.id===from),toIndex=visible.findIndex(item=>item.id===to);if(fromIndex<0||toIndex<0||fromIndex===toIndex)return;const ids=visible.map(item=>item.id),moved=ids.splice(fromIndex,1)[0];ids.splice(toIndex,0,moved);todayOrder=[...ids,...todayOrder.filter(id=>!ids.includes(id)),...actions.map(item=>item.id).filter(id=>!ids.includes(id)&&!todayOrder.includes(id))];saveTodayOrder();renderHome();showTodayFeedback(t('today.orderSaved'));return}let arr;if(scope==='actions')arr=actions.filter(item=>!item.done).sort((a,b)=>a.order-b.order);else if(scope==='projects')arr=projects.filter(project=>!project.archived).sort((a,b)=>a.order-b.order);else if(scope==='wishlist')arr=wishlist.filter(item=>item.bought===(wishlistFilter==='bought')&&(wishlistFilter==='bought'||purchaseFilter==='all'||item.purchaseType===purchaseFilter)).sort((a,b)=>a.order-b.order);else if(scope==='ideas')arr=ideas.slice().sort((a,b)=>a.order-b.order);else if(scope.startsWith('project:'))arr=actions.filter(item=>item.projectId===scope.slice(8)&&!item.done).sort((a,b)=>a.order-b.order);else if(scope.startsWith('list:'))arr=lists.find(list=>list.id===scope.slice(5)).items.slice().sort((a,b)=>a.order-b.order);if(!arr||!reorderItems(arr,from,to,scope.startsWith('list:')?(moved,target)=>moved.sublist=target?.sublist||moved.sublist:null))return;drag=null;if(scope==='projects')saveProjects();else if(scope==='wishlist')saveWishlist();else if(scope==='ideas')saveIdeas();else if(scope.startsWith('list:'))saveLists();else saveActions();refresh();if(scope.startsWith('list:'))renderListDetail()}
function moreButton(run){const b=document.createElement('button');b.className='more-button';b.textContent='•••';b.onclick=e=>{e.stopPropagation();run()};return b}
function menu(items){const box=$('bottomMenu');box.innerHTML='';items.forEach(i=>{const b=document.createElement('button');b.textContent=i.label;b.classList.toggle('menu-danger',!!i.danger);b.onclick=()=>{close('menuOverlay');i.run()};box.append(b)});const cancel=document.createElement('button');cancel.textContent='Annuleren';cancel.className='menu-cancel';cancel.onclick=()=>close('menuOverlay');box.append(cancel);open('menuOverlay')}
function confirmRemoval(action,message='Weet je zeker dat je dit wilt verwijderen?',confirmLabel='Ja, verwijderen'){pendingDeleteAction=action;$('confirmMessage').textContent=message;$('cancelDeleteButton').textContent='Terug';$('confirmDeleteButton').textContent=confirmLabel;open('confirmOverlay')}
$('cancelDeleteButton').onclick=()=>{pendingDeleteAction=null;close('confirmOverlay')};$('confirmDeleteButton').onclick=()=>{const action=pendingDeleteAction;pendingDeleteAction=null;close('confirmOverlay');action?.()};
function removeWithUndo(collection,item,save,after,message='Weet je zeker dat je dit wilt verwijderen?',toastTitle='Verwijderd'){confirmRemoval(()=>{const idx=collection.findIndex(x=>x.id===item.id),before=clone(item);collection.splice(idx,1);save();after?.();refresh();toast(toastTitle,item.title||item.name||item.text,'Ongedaan maken',()=>{collection.splice(idx,0,before);save();refresh()},3000)},message)}
function open(id){$(id).classList.remove('hidden');syncGlobalAdd()}function close(id){$(id).classList.add('hidden');if(['projectOverlay','wishlistOverlay','listOverlay'].includes(id))pendingInboxConversionId=null;syncGlobalAdd()}document.querySelectorAll('[data-close]').forEach(b=>b.onclick=()=>close(b.dataset.close));document.querySelectorAll('.overlay,.menu-overlay').forEach(o=>o.onclick=e=>{if(e.target===o&&o.id!=='confirmOverlay')close(o.id)});
function clearFieldError(input){input.classList.remove('field-error');input.parentElement?.querySelector('.field-error-message')?.remove()}
function requireField(input){if(input.value.trim()){clearFieldError(input);return true}input.classList.add('field-error');if(!input.parentElement?.querySelector('.field-error-message')){const message=document.createElement('small');message.className='field-error-message';message.textContent='Dit veld is verplicht.';input.insertAdjacentElement('afterend',message)}input.scrollIntoView({behavior:'smooth',block:'center'});input.focus();return false}
function clearChoiceError(container){container.classList.remove('choice-error');container.nextElementSibling?.classList.contains('choice-error-message')&&container.nextElementSibling.remove()}
function requireChoice(container,value){if(value){clearChoiceError(container);return true}clearChoiceError(container);container.classList.add('choice-error');const message=document.createElement('small');message.className='choice-error-message';message.textContent='Maak een keuze';container.insertAdjacentElement('afterend',message);return false}
document.addEventListener('input',e=>{if(e.target.matches('input,textarea'))clearFieldError(e.target)});
$('wishlistName').placeholder='Typ hier';
function toast(title,text,button,run,duration=4000){if(button==='Ongedaan maken'&&duration===4000)duration=3200;$('toastTitle').textContent=title;$('toastText').textContent=text||'';$('toastActionButton').textContent=button||'';$('toastActionButton').classList.toggle('hidden',!button);$('toastActionButton').onclick=()=>{run?.();close('toast')};open('toast');clearTimeout(window.toastTimer);window.toastTimer=setTimeout(()=>close('toast'),duration)}
const LUMI_PALETTE=['cyan','violet','rose','gold'];
function createLumi({mode='action',x=50,y=null}={}){const reduced=window.matchMedia('(prefers-reduced-motion: reduce)').matches;if(mode==='ambient'&&reduced)return null;const effect=document.createElement('i'),tone=LUMI_PALETTE[Math.floor(Math.random()*LUMI_PALETTE.length)];effect.className=`lumi lumi--${mode} lumi--${tone}`;effect.setAttribute('aria-hidden','true');effect.style.setProperty('--lumi-x',x+(typeof x==='number'?'vw':''));if(y!==null)effect.style.setProperty('--lumi-y',y+(typeof y==='number'?'vh':''));const direction=Math.random()>.5?1:-1,drift=direction*(18+Math.round(Math.random()*18));effect.style.setProperty('--lumi-drift-x',`${drift}px`);effect.style.setProperty('--lumi-drift-y',`${mode==='ambient'?-(34+Math.round(Math.random()*28)):-(58+Math.round(Math.random()*24))}px`);if(mode==='action'){const rise=Math.round(innerHeight*(.32+Math.random()*.03)),bend=direction*(20+Math.round(Math.random()*12));effect.style.offsetPath=`path("M 0 0 C ${-bend*.45} ${-rise*.28}, ${bend*1.05} ${-rise*.7}, ${bend} ${-rise}")`}document.body.append(effect);effect.addEventListener('animationend',()=>effect.remove(),{once:true});setTimeout(()=>effect.remove(),mode==='ambient'?8000:3000);return effect}
function lumiSuccess(){document.querySelector('.lumi--action')?.remove();createLumi({mode:'action'})}
function empty(parent,title,detail='',action=null){const e=document.createElement(action?'button':'div');e.className='soft-empty'+(action?' clickable-empty':'');const strong=document.createElement('strong');strong.textContent=title;e.append(strong);if(detail){const small=document.createElement('small');small.textContent=detail;e.append(small)}if(action)e.onclick=action;parent.append(e);return e}
function populateProjects(){$('actionProject').innerHTML='<option value="">Kies een project</option>';projects.filter(p=>!p.archived).forEach(p=>{const o=document.createElement('option');o.value=p.id;o.textContent=p.title;$('actionProject').append(o)})}
function refresh(){renderHome();renderMasterlist();renderWishlist();renderProjects();renderLists();renderIdeas();renderInbox();if(currentProjectId)renderProjectDetail();if(currentListId)renderListDetail()}
let pendingEnergy=energy;
function renderSettings(){if($('energySettingValue'))$('energySettingValue').textContent=energy?t('energy.settingsCurrent',{level:energy}):t('energy.settingsHelp')}
$('globalAddButton').onclick=()=>{if(currentScreen==='projects')openProject();else if(currentScreen==='projectDetail')openAction(null,currentProjectId);else if(currentScreen==='wishlist')openWishlist();else if(currentScreen==='lists')openList();else if(currentScreen==='ideas')openIdea();else if(currentScreen==='finance')openFinance();else if(currentScreen==='documents')openDocument();else openUniversalCapture()};
if($('feedbackSettingsButton'))$('feedbackSettingsButton').onclick=()=>{$('feedbackType').value=feedbackDraft.type||'';$('feedbackText').value=feedbackDraft.text||'';open('feedbackOverlay')};$('saveFeedbackDraftButton').onclick=()=>{feedbackDraft={type:$('feedbackType').value,text:$('feedbackText').value.trim(),updatedAt:Date.now()};write(KEYS.feedback,feedbackDraft);close('feedbackOverlay');toast('Concept bewaard','Alleen op dit apparaat')};
if($('calendarSettingsButton'))$('calendarSettingsButton').onclick=()=>toast('Apple Agenda is nog niet gekoppeld','Een beveiligde serververbinding is nodig; Apple-inloggegevens worden nooit in deze app opgeslagen.');
const energyCard=$('energyOverlay').querySelector('.modal-card');
// TODO: koppel submitFeedbackButton hier later aan de echte feedback-API; tot die tijd blijft verzenden bewust uitgeschakeld.
const navIcons={home:'<path d="M3.5 10.5 12 3.8l8.5 6.7V20a1 1 0 0 1-1 1h-5v-6h-5v6h-5a1 1 0 0 1-1-1z"/>',masterlist:'<path d="m5 7 2 2 4-4M5 13l2 2 4-4M13 7h6M13 13h6M5 19h14"/>',vault:'<rect x="4" y="4" width="16" height="16" rx="3"/><path d="M8 4v16M12 10h5"/>',projects:'<path d="M4 7.5h6l1.5 2H20v9.5a1 1 0 0 1-1 1H5a1 1 0 0 1-1-1z"/><path d="M4 7.5V6a1 1 0 0 1 1-1h5l1.5 2.5"/>',settings:'<circle cx="12" cy="12" r="3"/><path d="M19.4 15a1.7 1.7 0 0 0 .3 1.9l.1.1-2.8 2.8-.1-.1a1.7 1.7 0 0 0-1.9-.3 1.7 1.7 0 0 0-1 1.6v.2h-4V21a1.7 1.7 0 0 0-1-1.6 1.7 1.7 0 0 0-1.9.3l-.1.1L4.2 17l.1-.1a1.7 1.7 0 0 0 .3-1.9A1.7 1.7 0 0 0 3 14H2.8v-4H3a1.7 1.7 0 0 0 1.6-1 1.7 1.7 0 0 0-.3-1.9L4.2 7 7 4.2l.1.1a1.7 1.7 0 0 0 1.9.3A1.7 1.7 0 0 0 10 3V2.8h4V3a1.7 1.7 0 0 0 1 1.6 1.7 1.7 0 0 0 1.9-.3l.1-.1L19.8 7l-.1.1a1.7 1.7 0 0 0-.3-1.9 1.7 1.7 0 0 0 1.6 1h.2v4H21a1.7 1.7 0 0 0-1.6 1Z"/>'};document.querySelectorAll('.nav-button').forEach(button=>{button.querySelector('span').innerHTML=`<svg viewBox="0 0 24 24" aria-hidden="true">${navIcons[button.dataset.screen]}</svg>`});document.querySelectorAll('.module-card>span').forEach(icon=>icon.remove());document.querySelectorAll('.back-button').forEach(button=>{button.innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M14.5 5 7.5 12l7 7"/></svg>'});$('globalAddButton').innerHTML='<svg viewBox="0 0 24 24" aria-hidden="true"><path d="M12 5v14M5 12h14"/></svg>';$('globalAddButton').setAttribute('aria-label','Toevoegen');
