/** Home presentation only; recommendation selection lives in recommendations.js/today.js. */
function renderHomeScreen({$,sets,checkin,todayKey,suggestionCard,openCheckin,renderProjectPreview,broaden}){
  const attention=sets.attention||[],primary=sets.visible.slice(0,Math.max(0,3-attention.length)).map(entry=>entry.item),current=checkin.date===todayKey()?Number(checkin.energy)||null:null,card=$('todayContext'),locale=lumiLocale()==='en'?'en-GB':'nl-NL';
  $('homeDate').textContent=new Intl.DateTimeFormat(locale,{weekday:'long',day:'numeric',month:'long',year:'numeric'}).format(new Date()).replace(/^./,character=>character.toUpperCase());$('todayDate').textContent=new Intl.DateTimeFormat(locale,{day:'numeric',month:'long'}).format(new Date());
  $('todayEnergy').innerHTML=current?`<span class="energy-battery level-${current}" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></span>`:`<b>${t('energy.notSet')}</b>`;
  card.querySelector('.checkin-title').textContent=current?t('energy.currentTitle'):t('energy.homeQuestion');card.querySelector('.checkin-subtitle').textContent=current?t(`energy.status.${current}`):t('energy.homeHelp');card.querySelectorAll('.battery-bar').forEach((bar,index)=>bar.classList.toggle('filled',!!current&&index<current));$('todayAdjustButton').setAttribute('aria-label',current?t('energy.change'):t('energy.set'));$('todayAdjustButton').onclick=openCheckin;
  $('todayConsideration').textContent='';$('todayConsideration').classList.add('hidden');$('suggestionList').innerHTML='';$('moreTodayList').innerHTML='';$('moreTodayButton').classList.add('hidden');attention.slice(0,3).forEach(item=>$('suggestionList').append(waitingAttentionCard(item)));primary.forEach(item=>$('suggestionList').append(suggestionCard(item)));
  const noOptions=!primary.length&&!attention.length;$('suggestionEmpty').classList.toggle('hidden',!noOptions);if(noOptions)$('suggestionEmpty').innerHTML=`<strong>${t('today.emptyTitle')}</strong><small>${t('today.emptyHelp')}</small>`;
  const canBroaden=!broaden&&sets.standard.length<3&&sets.extra.length>0,recovery=$('todayRecoveryActions');$('broadenSuggestionsButton').classList.toggle('hidden',!canBroaden);recovery.classList.toggle('hidden',!canBroaden);recovery.style.setProperty('display',canBroaden?'block':'none','important');renderProjectPreview();
}
