function wishlistMenu(w){menu([{label:'Bewerken',run:()=>{close('wishlistDetailOverlay');openWishlist(w)}},{label:'Verwijderen',danger:true,run:()=>{close('wishlistDetailOverlay');removeWithUndo(wishlist,w,saveWishlist)}}])}

function normalizeList(l,n){const subs=Array.isArray(l.sublists)&&l.sublists.length?l.sublists:['main'];return{id:l.id||uid(),name:l.name||'Lijstje',type:l.type==='checklist'?'checklist':'list',color:l.color||'',sublists:subs,sublistColors:l.sublistColors&&typeof l.sublistColors==='object'?l.sublistColors:{},items:Array.isArray(l.items)?l.items.map((i,k)=>typeof i==='string'?{id:uid(),text:i,done:false,sublist:'main',order:k}:{...i,id:i.id||uid(),sublist:i.sublist||'main',order:Number.isFinite(+i.order)?+i.order:k}):[],order:Number.isFinite(+l.order)?+l.order:n,createdAt:l.createdAt||Date.now()}}
lists=lists.map(normalizeList);saveLists();
function renderLists(){const box=$('listsGrid');box.innerHTML='';lists.sort((a,b)=>a.order-b.order).forEach(l=>{const c=document.createElement('button');c.className='list-card'+(l.color?' list-thumb-'+l.color:'');c.innerHTML='<strong></strong>';c.querySelector('strong').textContent=l.name;c.onclick=()=>showList(l.id);box.append(c)});if(!lists.length)empty(box,'Nog geen lijstjes','Maak een lijstje',()=>openList())}
function openList(l=null){editingListId=l?.id||null;$('listModalTitle').textContent=l?'Lijstje bewerken':'Nieuw lijstje';$('listName').value=l?.name||'';selectedListType=l?.type||'list';selectedListColor=l?.color||'';document.querySelectorAll('[data-list-type]').forEach(b=>b.classList.toggle('selected',b.dataset.listType===selectedListType));document.querySelectorAll('[data-list-color]').forEach(b=>b.classList.toggle('selected',b.dataset.listColor===selectedListColor));open('listOverlay')}
document.querySelectorAll('[data-list-type]').forEach(b=>b.onclick=()=>{selectedListType=b.dataset.listType;document.querySelectorAll('[data-list-type]').forEach(x=>x.classList.toggle('selected',x===b))});
document.querySelectorAll('[data-list-color]').forEach(b=>b.onclick=()=>{selectedListColor=b.dataset.listColor;document.querySelectorAll('[data-list-color]').forEach(x=>x.classList.toggle('selected',x===b))});
$('saveListButton').onclick=()=>{if(!requireField($('listName')))return;const isNew=!editingListId,name=$('listName').value.trim();if(editingListId){const l=lists.find(x=>x.id===editingListId);Object.assign(l,{name,type:selectedListType,color:selectedListColor})}else lists.push({id:uid(),name,type:selectedListType,color:selectedListColor,sublists:['main'],sublistColors:{},items:[],order:lists.length,createdAt:Date.now()});saveLists();finishInboxConversion();close('listOverlay');refresh();if(editingListId)showList(editingListId);if(isNew)lumiSuccess()};
function showList(id){currentListId=id;currentSublist='main';showScreen('listDetail');renderListDetail()}
function renderListDetail(){const l=lists.find(x=>x.id===currentListId);if(!l)return showScreen('lists');$('listDetailTitle').textContent=l.name;$('listDetailType').textContent=l.type==='checklist'?'Checklist':'Lijstje';const board=$('listBoard');board.innerHTML='';const named=l.sublists.filter(s=>s!=='main'),columns=['main',...named];board.classList.toggle('single-board',columns.length===1);columns.forEach(sublist=>board.append(listColumn(l,sublist,sublist!=='main')));board.querySelectorAll('.column-empty').forEach(state=>{const main=state.closest('.board-column')?.dataset.sublist==='main';state.innerHTML=`<strong>${main?'Deze lijst is nog leeg':'Deze sublijst is nog leeg'}</strong><small>Voeg iets toe</small>`})}
function listColumn(l,sublist,organized){const column=document.createElement('section'),color=l.sublistColors?.[sublist]||'';column.className='board-column'+(color?' sublist-'+color:'');column.dataset.sublist=sublist;if(organized){const head=document.createElement('header'),title=document.createElement('h3');title.textContent=sublist==='main'?'Overig':sublist;head.append(title);if(sublist!=='main'){const controls=document.createElement('button');controls.className='column-menu';controls.textContent='•••';controls.onclick=()=>menu([{label:'Sublijst bewerken',run:()=>openSublist(l,sublist)},{label:'Sublijst verwijderen',danger:true,run:()=>{const count=l.items.filter(i=>i.sublist===sublist).length;confirmRemoval(()=>{const before=clone(l),index=lists.findIndex(x=>x.id===l.id);l.sublists=l.sublists.filter(s=>s!==sublist);l.items=l.items.filter(i=>i.sublist!==sublist);delete l.sublistColors[sublist];saveLists();renderListDetail();toast('Sublijst verwijderd',sublist,'Ongedaan maken',()=>{lists[index]=before;saveLists();renderListDetail()},3000)},count?`Weet je zeker dat je deze sublijst en de ${count} items wilt verwijderen?`:'Weet je zeker dat je deze sublijst wilt verwijderen?')}}]);head.append(controls)}column.append(head)}const items=document.createElement('ul');items.className='stack-list board-items';l.items.filter(i=>i.sublist===sublist).sort((a,b)=>a.order-b.order).forEach(i=>items.append(listItemRow(l,i)));if(!items.children.length){const e=document.createElement('li');e.className='column-empty';e.textContent='Nog geen items';items.append(e)}const add=document.createElement('div');add.className='inline-add board-add';const input=document.createElement('input');input.className='main-input';input.placeholder='Nieuw item';const button=document.createElement('button');button.className='primary-button';button.textContent='+';const save=()=>{if(!requireField(input))return;const text=input.value.trim();l.items.push({id:uid(),text,done:false,sublist,order:l.items.length});saveLists();renderListDetail();setTimeout(()=>document.querySelector(`.board-column[data-sublist="${CSS.escape(sublist)}"] .board-add input`)?.focus(),0)};button.onclick=save;input.onkeydown=e=>{if(e.key==='Enter')save()};add.append(input,button);column.append(items,add);return column}
function listItemRow(l,i){const row=document.createElement('li');row.className='task-row';row.classList.toggle('completed',!!i.done);row.dataset.id=i.id;row.dataset.sublist=i.sublist;if(l.type==='checklist'){const c=document.createElement('button');c.className='check'+(i.done?' checked':'');c.textContent=i.done?'✓':'';c.onclick=()=>{i.done=!i.done;saveLists();renderListDetail()};row.append(c)}const text=document.createElement('button');text.className='plain-item';text.textContent=i.text;text.onclick=()=>row.classList.toggle('controls-visible');row.append(text,moreButton(()=>menu([{label:'Bewerken',run:()=>{const v=prompt('Item bewerken',i.text);if(v?.trim()){i.text=v.trim();saveLists();renderListDetail()}}},{label:'Verwijderen',danger:true,run:()=>confirmRemoval(()=>{const index=l.items.findIndex(x=>x.id===i.id),before=clone(i);l.items.splice(index,1);saveLists();renderListDetail();toast('Verwijderd',i.text,'Ongedaan maken',()=>{l.items.splice(index,0,before);saveLists();renderListDetail()},3000)})}])));wireDrag(row,'list:'+l.id);return row}
function openSublist(l,name=null){editingSublistName=name;selectedSublistColor=name?l.sublistColors?.[name]||'':'';$('sublistModalTitle').textContent=name?'Sublijst bewerken':'Nieuw sublijstje';$('sublistName').value=name||'';document.querySelectorAll('[data-sublist-color]').forEach(b=>b.classList.toggle('selected',b.dataset.sublistColor===selectedSublistColor));open('sublistOverlay');setTimeout(()=>$('sublistName').focus(),50)}
document.querySelectorAll('[data-sublist-color]').forEach(b=>b.onclick=()=>{selectedSublistColor=b.dataset.sublistColor;document.querySelectorAll('[data-sublist-color]').forEach(x=>x.classList.toggle('selected',x===b))});
$('addSublistButton').onclick=()=>{const l=lists.find(x=>x.id===currentListId);if(l)openSublist(l)};$('saveSublistButton').onclick=()=>{const l=lists.find(x=>x.id===currentListId);if(!l||!requireField($('sublistName')))return;const clean=$('sublistName').value.trim();l.sublistColors=l.sublistColors||{};if(editingSublistName){l.sublists=l.sublists.map(s=>s===editingSublistName?clean:s);l.items.forEach(i=>{if(i.sublist===editingSublistName)i.sublist=clean});delete l.sublistColors[editingSublistName]}else if(!l.sublists.includes(clean))l.sublists.push(clean);if(selectedSublistColor)l.sublistColors[clean]=selectedSublistColor;editingSublistName=null;saveLists();close('sublistOverlay');renderListDetail()};$('sublistName').onkeydown=e=>{if(e.key==='Enter')$('saveSublistButton').click()};$('listBackButton').onclick=()=>showScreen('lists');$('editListButton').onclick=()=>{const l=lists.find(x=>x.id===currentListId);menu([{label:'Bewerken',run:()=>openList(l)},{label:'Verwijderen',danger:true,run:()=>removeWithUndo(lists,l,saveLists,()=>showScreen('lists'),'Weet je zeker dat je dit lijstje wilt verwijderen?','Lijstje verwijderd')}])};

