/* Rollout 7: progressive disclosure and shared Vault presentation. */
const suggestionCardR7=suggestionCard;suggestionCard=function(item,secondary=false){const card=suggestionCardR7(item,secondary),projectLabel=card.querySelector('.suggestion-project');if(projectLabel)projectLabel.textContent=displayProjectName(projectLabel.textContent);card.querySelector('.recommendation-why')?.remove();const swap=card.querySelector('.swap-button');if(swap)swap.innerHTML='<span aria-hidden="true">⇄</span> Wissel taak';return card};

openTaskDetail=function(item){$('taskDetailTitle').textContent=item.title;const project=projects.find(entry=>entry.id===item.projectId),projectLabel=$('taskDetailProject');projectLabel.textContent=project?.title||'';projectLabel.classList.toggle('hidden',!project);$('taskDetailMeta').innerHTML='';$('taskDetailEditButton').onclick=()=>{close('taskDetailOverlay');openAction(item)};$('taskDetailDeleteButton').onclick=()=>{close('taskDetailOverlay');removeWithUndo(actions,item,saveActions,()=>showScreen(detailOrigin==='projectDetail'?'projectDetail':detailOrigin==='masterlist'?'masterlist':'home'),'Weet je zeker dat je deze taak wilt verwijderen?')};open('taskDetailOverlay')};

document.querySelectorAll('[data-form-extra]').forEach(button=>button.onclick=()=>{const panel=$(button.dataset.formExtra),willOpen=panel.classList.contains('hidden');panel.classList.toggle('hidden',!willOpen);button.classList.toggle('open',willOpen);button.setAttribute('aria-expanded',String(willOpen))});
function setFormExtra(id,open){const panel=$(id),button=document.querySelector(`[data-form-extra="${id}"]`);panel.classList.toggle('hidden',!open);button.classList.toggle('open',open);button.setAttribute('aria-expanded',String(open))}
const openFinanceR7=openFinance;openFinance=function(item=null){openFinanceR7(item);const hasExtra=!!item&&(!!item.date||!!item.dueDate||item.status!=='open'||!!item.note);setFormExtra('financeExtra',hasExtra);const parties=[...new Set(financeItems.map(entry=>entry.party?.trim()).filter(Boolean))].sort((a,b)=>a.localeCompare(b,'nl'));$('financePartySuggestions').innerHTML=parties.map(party=>`<option value="${party.replaceAll('"','&quot;')}"></option>`).join('')};
const openDocumentR7=openDocument;openDocument=function(item=null){openDocumentR7(item);const hasExtra=!!item&&(!!item.category||!!item.date||!!item.party||item.amount!==''||item.tags?.length||!!item.note);setFormExtra('documentExtra',hasExtra)};

document.querySelector('[data-wishlist-unified="done"]').onclick=()=>{wishlistFilter='bought';purchaseFilter='all';document.querySelectorAll('#purchaseTypeFilters button').forEach(button=>button.classList.toggle('selected',button.dataset.wishlistUnified==='done'));renderWishlist()};
document.querySelectorAll('#purchaseTypeFilters [data-purchase-filter]').forEach(button=>button.addEventListener('click',()=>{wishlistFilter='open';document.querySelectorAll('#purchaseTypeFilters button').forEach(other=>other.classList.toggle('selected',other===button));renderWishlist()}));
const renderWishlistR7=renderWishlist;renderWishlist=function(){renderWishlistR7();$('purchaseTypeFilters').classList.remove('hidden');document.querySelectorAll('#purchaseTypeFilters button').forEach(button=>button.classList.toggle('selected',wishlistFilter==='bought'?button.dataset.wishlistUnified==='done':button.dataset.purchaseFilter===purchaseFilter))};

function financeItemRow(item){const row=document.createElement('article'),remaining=Math.max(0,item.amount-item.paid);row.className='vault-item finance-item';row.innerHTML='<div><strong></strong><small></small></div>';row.querySelector('strong').textContent=item.title;row.querySelector('small').textContent=`${item.direction==='receive'?'Te ontvangen':'Te betalen'} · ${formatPrice(item.status==='partial'?remaining:item.amount)}${item.date?' · '+formatDate(item.date):''}`;row.append(moreButton(()=>menu([{label:'Bewerken',run:()=>openFinance(item)},{label:'Verwijderen',danger:true,run:()=>removeWithUndo(financeItems,item,saveFinance,renderFinance)}])));return row}
renderFinance=function(){const box=$('financeList');box.innerHTML='';const items=financeItems.filter(item=>financeFilter==='done'?item.status==='done':item.status!=='done').sort((a,b)=>a.order-b.order);if(!items.length)return empty(box,financeFilter==='done'?'Nog niets afgehandeld':'Geen financiële losse eindjes','Voeg iets toe',()=>openFinance());const grouped=new Map(),ungrouped=[];items.forEach(item=>{const party=item.party?.trim();if(!party)return ungrouped.push(item);if(!grouped.has(party))grouped.set(party,[]);grouped.get(party).push(item)});grouped.forEach((entries,party)=>{const details=document.createElement('details');details.className='finance-group';const total=entries.reduce((sum,item)=>sum+Math.max(0,item.amount-item.paid),0),summary=document.createElement('summary');summary.innerHTML='<span><strong></strong><small></small></span><i class="ph ph-caret-down" aria-hidden="true"></i>';summary.querySelector('strong').textContent=party;summary.querySelector('small').textContent=`${formatPrice(total)} ${entries.every(item=>item.direction==='receive')?'te ontvangen':entries.every(item=>item.direction==='pay')?'te betalen':'openstaand'} · ${entries.length} ${entries.length===1?'item':'items'}`;details.append(summary);const list=document.createElement('div');list.className='finance-group-items';entries.forEach(item=>list.append(financeItemRow(item)));details.append(list);box.append(details)});ungrouped.forEach(item=>box.append(financeItemRow(item)))};

const vaultIcons={wishlistModule:'heart',listsModule:'list-checks',ideasModule:'lightbulb',inboxModule:'tray',financeModule:'wallet',documentsModule:'files'};Object.entries(vaultIcons).forEach(([id,icon])=>{const card=$(id);card.querySelector('.vault-icon')?.remove();const holder=document.createElement('span');holder.className='vault-icon';holder.innerHTML=`<i class="ph ph-${icon}" aria-hidden="true"></i>`;card.prepend(holder)});
document.querySelectorAll('.modal-close').forEach(button=>{if(!button.classList.contains('capture-save'))button.textContent=''});

