let selectedProjectIcon='folder',projectView='active';
function renderProjects(){const box=$('projectsList');box.innerHTML='';const archived=projectView==='completed',visible=projects.filter(project=>!!project.archived===archived).sort((a,b)=>a.order-b.order);if(!visible.length)return empty(box,t(archived?'project.completed':'project.active'),'',archived?undefined:()=>openProject());visible.forEach(project=>box.append(projectCard(project,true)))}
function renderProjectPreview(){const box=$('projectCarousel');box.innerHTML='';projects.filter(p=>!p.archived).sort((a,b)=>a.order-b.order).slice(0,6).forEach(p=>box.append(projectCard(p,false)));if(!box.children.length)empty(box,'Nog geen projecten')}
function projectCard(project,draggable){const card=document.createElement('div');card.className=`project-card project-${project.color}`;card.dataset.id=project.id;const main=document.createElement('button');main.className='project-card-main';main.innerHTML=`<span class="project-card-icon"><i class="ph ph-${project.icon||'folder'}"></i></span><h3></h3><small>${project.archived?t('project.completed'):t('project.active')}</small>`;main.querySelector('h3').textContent=project.title;main.onclick=()=>showProjectDetail(project.id);card.append(main);if(draggable)wireDrag(card,'projects');card.append(moreButton(()=>projectMenu(project)));return card}
function showProjectDetail(id){currentProjectId=id;showScreen('projectDetail');renderProjectDetail()}
function renderProjectDetail(){const p=projects.find(x=>x.id===currentProjectId);if(!p)return showScreen('projects');$('projectDetailScreen').dataset.projectColor=p.color;$('projectDetailTitle').textContent=p.title;const box=$('projectActionList');box.innerHTML='';const items=actions.filter(a=>a.projectId===p.id&&!a.done).sort((a,b)=>a.order-b.order);items.forEach(i=>box.append(taskRow(i,true,'project:'+p.id)));if(!items.length)empty(box,'Nog geen taken','Voeg een taak toe',()=>openAction(null,p.id))}
$('projectBackButton').onclick=()=>{currentProjectId=null;showScreen('projects')};$('projectDetailMenuButton').onclick=()=>projectMenu(projects.find(p=>p.id===currentProjectId));
function openProject(project=null){editingProjectId=project?.id||null;$('projectName').value=project?.title||'';selectedColor=project?.color||'purple';selectedProjectIcon=project?.icon||'folder';$('projectModalEyebrow').textContent=project?t('project.edit'):t('project.new');document.querySelectorAll('.color-choice').forEach(button=>button.classList.toggle('selected',button.dataset.color===selectedColor));document.querySelectorAll('[data-project-icon]').forEach(button=>button.classList.toggle('selected',button.dataset.projectIcon===selectedProjectIcon));open('projectOverlay')}
document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{selectedColor=b.dataset.color;document.querySelectorAll('[data-color]').forEach(x=>x.classList.toggle('selected',x===b))});
$('saveProjectButton').onclick=()=>{if(!requireField($('projectName')))return;const isNew=!editingProjectId,title=$('projectName').value.trim(),existing=projects.find(project=>project.id===editingProjectId);if(existing)Object.assign(existing,{title,color:selectedColor,icon:selectedProjectIcon});else projects.push({id:uid(),title,color:selectedColor,icon:selectedProjectIcon,archived:false,order:projects.length,createdAt:Date.now()});saveProjects();finishInboxConversion();close('projectOverlay');refresh();if(isNew)lumiSuccess()};
function projectMenu(project){if(!project)return;menu([{label:t('menu.edit'),run:()=>openProject(project)},{label:project.archived?t('project.reopen'):t('project.archive'),run:()=>{project.archived=!project.archived;saveProjects();renderProjects()}},{label:t('menu.delete'),danger:true,run:()=>confirmRemoval(()=>{projects=projects.filter(entry=>entry.id!==project.id);actions.forEach(action=>{if(action.projectId===project.id)action.projectId=''});saveProjects();saveActions();showScreen('projects')})}])}
