function renderProjects(){const box=$('projectsList');box.innerHTML='';const active=projects.filter(p=>!p.archived).sort((a,b)=>a.order-b.order);if(!active.length)return empty(box,'Nog geen projecten','Voeg een project toe',()=>openProject());active.forEach(p=>box.append(projectCard(p,true)))}
function renderProjectPreview(){const box=$('projectCarousel');box.innerHTML='';projects.filter(p=>!p.archived).sort((a,b)=>a.order-b.order).slice(0,6).forEach(p=>box.append(projectCard(p,false)));if(!box.children.length)empty(box,'Nog geen projecten')}
function projectCard(p,draggable){const card=document.createElement('div');card.className='project-card project-'+p.color;card.dataset.id=p.id;const main=document.createElement('button');main.className='project-card-main';main.innerHTML='<h3></h3>';main.firstChild.textContent=p.title;main.onclick=()=>showProjectDetail(p.id);card.append(main);if(draggable)wireDrag(card,'projects');card.append(moreButton(()=>projectMenu(p)));return card}
function showProjectDetail(id){currentProjectId=id;showScreen('projectDetail');renderProjectDetail()}
function renderProjectDetail(){const p=projects.find(x=>x.id===currentProjectId);if(!p)return showScreen('projects');$('projectDetailScreen').dataset.projectColor=p.color;$('projectDetailTitle').textContent=p.title;const box=$('projectActionList');box.innerHTML='';const items=actions.filter(a=>a.projectId===p.id&&!a.done).sort((a,b)=>a.order-b.order);items.forEach(i=>box.append(taskRow(i,true,'project:'+p.id)));if(!items.length)empty(box,'Nog geen taken','Voeg een taak toe',()=>openAction(null,p.id))}
$('projectBackButton').onclick=()=>{currentProjectId=null;showScreen('projects')};$('projectDetailMenuButton').onclick=()=>projectMenu(projects.find(p=>p.id===currentProjectId));
function openProject(p=null){editingProjectId=p?.id||null;$('projectName').value=p?.title||'';selectedColor=p?.color||'purple';$('projectModalEyebrow').textContent=p?'Project bewerken':'Nieuw project';document.querySelectorAll('.color-choice').forEach(b=>b.classList.toggle('selected',b.dataset.color===selectedColor));open('projectOverlay')}
document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{selectedColor=b.dataset.color;document.querySelectorAll('[data-color]').forEach(x=>x.classList.toggle('selected',x===b))});
$('saveProjectButton').onclick=()=>{if(!requireField($('projectName')))return;const isNew=!editingProjectId,title=$('projectName').value.trim();if(editingProjectId)Object.assign(projects.find(p=>p.id===editingProjectId),{title,color:selectedColor});else projects.push({id:uid(),title,color:selectedColor,archived:false,order:projects.length,createdAt:Date.now()});saveProjects();finishInboxConversion();close('projectOverlay');refresh();if(isNew)lumiSuccess()};
function projectMenu(p){if(!p)return;menu([{label:'Bewerken',run:()=>openProject(p)},{label:'Verwijderen',danger:true,run:()=>confirmRemoval(()=>{const index=projects.findIndex(x=>x.id===p.id),before=clone(p),affected=actions.filter(a=>a.projectId===p.id).map(a=>a.id);projects=projects.filter(x=>x.id!==p.id);actions.forEach(a=>{if(a.projectId===p.id)a.projectId=''});saveProjects();saveActions();showScreen('projects');toast('Verwijderd',p.title,'Ongedaan maken',()=>{projects.splice(index,0,before);actions.forEach(a=>{if(affected.includes(a.id))a.projectId=before.id});saveProjects();saveActions();refresh()},3000)})}])}

