/** Task capture draft lifecycle and the single active check-in controller. */
const checkinFeature=setupCheckinFeature({$,energyCard,todayKey,getCheckin:()=>checkin,getPendingEnergy:()=>pendingEnergy,setPendingEnergy:value=>{pendingEnergy=value},setEnergy:value=>{energy=value},setCheckin:value=>{checkin=value},write,keys:KEYS,open,close,renderHome:()=>renderHome(),renderSettings:()=>renderSettings(),lumiSuccess});
openCheckin=checkinFeature.openCheckin;
if($('settingsEnergyButton'))$('settingsEnergyButton').onclick=openCheckin;$('homeCheckinButton').onclick=openCheckin;$('adjustCheckinButton').onclick=openCheckin;$('todayEnergy').onclick=openCheckin;

function returnToCaptureTypes(){captureDraft.task={title:$('actionTitle').value,importance:formImportance,impact:formImpact,resistance:formResistance,load:formLoad,reasons:selectedResistanceReasons.slice(),duration:$('duration').value};$('universalCaptureText').value=$('actionTitle').value||$('universalCaptureText').value;open('captureTypeOverlay')}
function closeCaptureFlow(){const changed=!!editingActionId||!!$('actionTitle').value.trim()||!!formImportance||!!formImpact||!!formResistance||!!formLoad||selectedResistanceReasons.length>0,leave=()=>{captureDraft={};pendingInboxConversionId=null;close('captureTypeOverlay');currentProjectId?showProjectDetail(currentProjectId):showScreen(previousScreen==='capture'?'home':previousScreen)};if(!changed)return leave();confirmRemoval(leave,t('capture.closeConfirm'),t('capture.close'))}

const durationGrid=document.createElement('div');durationGrid.className='duration-choice-grid';Array.from($('duration').options).filter(option=>option.value).forEach(option=>{const button=document.createElement('button');button.type='button';button.dataset.duration=option.value;button.textContent=option.textContent;button.onclick=()=>{$('duration').value=option.value;activeActionExtras.add('duration');durationGrid.querySelectorAll('button').forEach(other=>other.classList.toggle('selected',other===button));updateActionExtraSummaries();setDisclosure('duration',false)};durationGrid.append(button)});$('duration').classList.add('duration-native-fallback');$('duration').after(durationGrid);

function collectActionDraft(){return{editingId:editingActionId,title:$('actionTitle').value,importance:formImportance,impact:formImpact,resistance:formResistance,load:formLoad,reasons:selectedResistanceReasons.slice(),extras:[...activeActionExtras],duration:$('duration').value,deadline:$('deadlineDate').value,deadlineText:$('deadlineDateText').value,project:$('actionProject').value,repeatEvery:$('repeatEvery').value,repeatUnit:$('repeatUnit').value,lastDone:$('lastDone').value,note:$('actionNote').value,context:activeTaskContext,updatedAt:Date.now()}}
function persistActionDraft(){const draft=collectActionDraft();captureDraft.task=draft;write(KEYS.actionDraft,draft)}
function clearActionDraft(){captureDraft={};localStorage.removeItem(KEYS.actionDraft)}
function restoreActionDraft(draft){if(!draft)return;$('actionTitle').value=draft.title??'';formImportance=draft.importance??null;formImpact=draft.impact??null;formResistance=draft.resistance??null;formLoad=draft.load??null;activeTaskContext=draft.context==='household'?'household':activeTaskContext;selectedResistanceReasons=Array.isArray(draft.reasons)?draft.reasons.slice():[];activeActionExtras=new Set(draft.extras||[]);$('duration').value=draft.duration||'';setDeadlineValue(draft.deadline||'');$('deadlineDateText').value=draft.deadlineText||$('deadlineDateText').value;populateProjects();$('actionProject').value=draft.project||'';$('repeatEvery').value=draft.repeatEvery||1;$('repeatUnit').value=draft.repeatUnit||'weeks';$('lastDone').value=draft.lastDone||'';$('actionNote').value=draft.note||'';renderResistanceReasons();[['importanceChoices',formImportance],['impactChoices',formImpact],['resistanceChoices',formResistance],['loadChoices',formLoad]].forEach(([id,value])=>document.querySelectorAll(`#${id} button`).forEach(button=>button.classList.toggle('selected',+button.dataset.value===value)));document.querySelectorAll('[data-disclosure]').forEach(button=>setDisclosure(button.dataset.disclosure,activeActionExtras.has(button.dataset.disclosure)));setTaskContextVisible(!!(formImpact||formResistance||formLoad||activeActionExtras.size));updateActionExtraSummaries();durationGrid.querySelectorAll('button').forEach(button=>button.classList.toggle('selected',button.dataset.duration===$('duration').value))}
function prepareActionCapture(item){const saved=read(KEYS.actionDraft,null);if(saved&&((item&&saved.editingId===item.id)||(!item&&!saved.editingId)))restoreActionDraft(saved);durationGrid.querySelectorAll('button').forEach(button=>button.classList.toggle('selected',button.dataset.duration===$('duration').value));$('captureCloseButton').classList.toggle('capture-save',!!item);$('captureCloseButton').textContent=item?'✓':'×';$('captureCloseButton').setAttribute('aria-label',item?t('capture.saveChanges'):t('capture.close'));$('captureCloseButton').onclick=item?requestActionSave:()=>{persistActionDraft();showScreen(previousScreen==='capture'?'home':previousScreen)}}
function requestActionSave(){if(typeof $('actionForm').requestSubmit==='function')$('actionForm').requestSubmit();else $('actionForm').dispatchEvent(new Event('submit',{bubbles:true,cancelable:true}))}
document.querySelectorAll('#actionForm input,#actionForm textarea,#actionForm select').forEach(field=>{field.addEventListener('input',persistActionDraft);field.addEventListener('change',persistActionDraft)});document.querySelectorAll('#actionForm button[type="button"]').forEach(button=>button.addEventListener('click',()=>setTimeout(persistActionDraft,0)));
$('captureBackButton').onclick=()=>{persistActionDraft();if(editingActionId)showScreen(detailOrigin==='projectDetail'?'projectDetail':detailOrigin==='masterlist'?'masterlist':'home');else returnToCaptureTypes()};$('captureTypeOverlay').querySelector('.modal-close').onclick=()=>{if(currentScreen==='capture')closeCaptureFlow();else close('captureTypeOverlay')};$('cancelActionButton').onclick=()=>confirmRemoval(()=>{clearActionDraft();pendingInboxConversionId=null;currentProjectId?showProjectDetail(currentProjectId):showScreen('home')},t('capture.deleteDraftConfirm'),t('capture.deleteDraft'));
let financeFilter='open',editingFinanceId=null,financeDirection='receive';
