let activeTaskContext='general';
$('moreTodayButton').onclick=()=>{$('moreTodayList').classList.toggle('hidden');$('moreTodayButton').classList.toggle('open')};$('homeCheckinButton').onclick=()=>open('energyOverlay');
function checkButton(item,row){const button=document.createElement('button');button.className='check'+(item.done?' checked':'');button.textContent=item.done?'✓':'';button.onclick=()=>{if(item.done){item.done=false;item.lifecycle={...item.lifecycle,state:TASK_STATES.OPEN};saveActions();refresh();return}button.disabled=true;button.classList.add('checked');button.textContent='✓';row.classList.add('finishing');setTimeout(()=>complete(item),360)};return button}
function complete(item){const before=clone(item),completed=completeTaskOccurrence(item,{completedDate:todayKey()});Object.assign(item,completed);saveActions();undo={kind:'action',before};toast(t('task.completed'),item.title,t('undo'),()=>{const index=actions.findIndex(entry=>entry.id===before.id);if(index>=0)actions[index]=before;saveActions();refresh()});refresh()}

function renderMasterlist(){const query=$('masterSearch').value.trim().toLowerCase(),visible=actions.filter(item=>{if(isHouseholdTask(item))return false;const relevance=getTaskRelevance(item,{today:todayKey()}),state=item.done?'done':relevance.state;return state===masterFilter&&item.title.toLowerCase().includes(query)}).sort((a,b)=>a.order-b.order),list=$('masterlistList');list.innerHTML='';if(!visible.length){if(query)return empty(list,t('masterlist.noResults'),t('masterlist.adjustSearch'));const copy={done:[t('masterlist.emptyDone'),t('masterlist.emptyDoneHelp')],waiting:[t('masterlist.emptyWaiting'),t('masterlist.emptyWaitingHelp')],later:[t('masterlist.emptyLater'),t('masterlist.emptyLaterHelp')],open:[t('masterlist.emptyOpen'),t('masterlist.emptyOpenHelp')]}[masterFilter];return empty(list,copy[0],copy[1],masterFilter==='open'?()=>openAction():undefined)}visible.forEach(item=>list.append(taskRow(item,masterFilter==='open'&&!query,'actions')))}
function taskRow(item,draggable=false,scope='actions'){const li=document.createElement('li');li.className='task-row'+(item.done?' completed':'');li.dataset.id=item.id;li.tabIndex=0;li.setAttribute('role','group');li.setAttribute('aria-label',`${item.title} bekijken`);const project=projects.find(p=>p.id===item.projectId),showProject=project&&!scope.startsWith('project:'),content=document.createElement('div');content.className='task-row-content';content.innerHTML=`${showProject?'<small class="suggestion-project"></small>':''}<div class="task-row-title"></div>`;if(showProject)content.querySelector('.suggestion-project').textContent=displayProjectName(project.title);content.querySelector('.task-row-title').textContent=item.title;const meta=[];if(item.dueDate)meta.push(t('date.deadline')+' '+formatDateLong(item.dueDate));if(item.plannedDate)meta.push(t('date.planned')+' '+formatDateLong(item.plannedDate));if(item.lifecycle?.state===TASK_STATES.WAITING&&item.waitingSince)meta.push(t('waiting.since',{date:formatDateLong(item.waitingSince)}));if(item.lifecycle?.state===TASK_STATES.LATER&&item.resurfaceDate)meta.push(t('date.resurface')+' '+formatDateLong(item.resurfaceDate));if(item.note)meta.push('Notitie');if(meta.length){const sm=document.createElement('small');sm.className='task-meta';sm.textContent=meta.join(' · ');content.append(sm)}const more=moreButton(()=>actionMenu(item));li.append(checkButton(item,li),content,more);li.onclick=e=>{if(e.target.closest('.check,.more-button'))return;openTaskDetail(item)};li.onkeydown=e=>{if((e.key==='Enter'||e.key===' ')&&!e.target.closest('.check,.more-button')){e.preventDefault();openTaskDetail(item)}};if(draggable)wireDrag(li,scope);return li}
$('masterSearch').oninput=renderMasterlist;document.querySelectorAll('.list-tab').forEach(b=>b.onclick=()=>{masterFilter=b.dataset.masterFilter;document.querySelectorAll('.list-tab').forEach(x=>x.classList.toggle('active',x===b));renderMasterlist()});
function promptTaskDate(message,current=''){const value=prompt(message,current)?.trim();if(value==null)return null;if(value&&!validIsoDate(value)){alert(t('date.invalid'));return null}return value}
function waitTask(item){const waitingFor=prompt(t('waiting.forPrompt'),item.waitingFor||'');if(waitingFor==null)return;setTaskWaiting(item,{waitingFor:waitingFor.trim(),followUpDate:''});saveActions();openResurfaceCalendar(item,'waiting')}
let pendingResurfaceTask=null,resurfaceView=new Date();
function renderResurfaceCalendar(){const year=resurfaceView.getFullYear(),month=resurfaceView.getMonth(),first=new Date(year,month,1),offset=(first.getDay()+6)%7,last=new Date(year,month+1,0).getDate();$('resurfaceMonth').textContent=first.toLocaleDateString(lumiLocale()==='en'?'en-GB':'nl-NL',{month:'long',year:'numeric'});$('resurfaceDays').innerHTML='';for(let i=0;i<offset;i++)$('resurfaceDays').append(document.createElement('span'));for(let day=1;day<=last;day++){const button=document.createElement('button'),iso=`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;button.type='button';button.textContent=day;button.classList.toggle('today',iso===todayKey());button.classList.toggle('selected',iso===pendingResurfaceTask?.resurfaceDate||iso===pendingResurfaceTask?.followUpDate);button.onclick=()=>applyResurfaceDate(iso);$('resurfaceDays').append(button)}}
function openResurfaceCalendar(item,mode='later'){pendingResurfaceTask={item,mode,resurfaceDate:item.resurfaceDate||'',followUpDate:item.followUpDate||''};const selected=pendingResurfaceTask.resurfaceDate||pendingResurfaceTask.followUpDate;resurfaceView=selected?new Date(selected+'T12:00'):new Date();renderResurfaceCalendar();open('resurfaceOverlay')}
function applyResurfaceDate(date=''){if(!pendingResurfaceTask)return;const{item,mode}=pendingResurfaceTask;if(mode==='waiting')keepTaskWaiting(item,date);else setTaskLater(item,date);saveActions();pendingResurfaceTask=null;close('resurfaceOverlay');refresh()}
$('resurfacePrev').onclick=()=>{resurfaceView=new Date(resurfaceView.getFullYear(),resurfaceView.getMonth()-1,1);renderResurfaceCalendar()};$('resurfaceNext').onclick=()=>{resurfaceView=new Date(resurfaceView.getFullYear(),resurfaceView.getMonth()+1,1);renderResurfaceCalendar()};$('resurfaceNoDate').onclick=()=>applyResurfaceDate('');
function laterTask(item){openResurfaceCalendar(item,'later')}
function followUpTask(item){makeTaskActionable(item);saveActions();refresh()}
function keepWaitingTask(item){openResurfaceCalendar(item,'waiting')}
function actionMenu(item){const state=getTaskRelevance(item,{today:todayKey()}).state,items=[{label:t('menu.edit'),run:()=>{close('taskDetailOverlay');openAction(item)}}];if(state===TASK_STATES.WAITING)items.push({label:t('waiting.keep'),run:()=>keepWaitingTask(item)},{label:t('waiting.followUp'),run:()=>followUpTask(item)});else if(state===TASK_STATES.LATER)items.push({label:t('later.resurface'),run:()=>followUpTask(item)},{label:t('waiting.set'),run:()=>waitTask(item)});else items.push({label:t('waiting.set'),run:()=>waitTask(item)},{label:t('later.set'),run:()=>laterTask(item)});items.push({label:t('menu.delete'),danger:true,run:()=>{close('taskDetailOverlay');removeWithUndo(actions,item,saveActions,()=>showScreen(detailOrigin==='projectDetail'?'projectDetail':detailOrigin==='masterlist'?'masterlist':'home'),'Weet je zeker dat je deze taak wilt verwijderen?')}});menu(items)}

function waitingAttentionCard(item){const li=document.createElement('li');li.className='suggestion-card waiting-attention';const content=document.createElement('div');content.className='suggestion-content';const title=document.createElement('div');title.className='suggestion-text';title.textContent=item.waitingFor?t('waiting.noResponse',{name:item.waitingFor}):item.title;const meta=document.createElement('small');meta.className='recommendation-why';meta.textContent=item.waitingSince?t('waiting.since',{date:formatDateLong(item.waitingSince)}):t('waiting.generic');const actions=document.createElement('div');actions.className='waiting-actions';[[t('waiting.keep'),()=>keepWaitingTask(item)],[t('waiting.followUp'),()=>followUpTask(item)]].forEach(([label,run])=>{const button=document.createElement('button');button.type='button';button.textContent=label;button.onclick=run;actions.append(button)});content.append(title,meta);li.append(content,actions);return li}

function setDisclosure(name,open=false){const button=document.querySelector(`[data-disclosure="${name}"]`),panel=$(name+'Fields');button?.closest('.disclosure-item')?.classList.toggle('open',open);button?.setAttribute('aria-expanded',String(open));panel?.classList.toggle('hidden',!open)}
let calendarView=new Date();
function renderDeadlineCalendar(){const selected=$('deadlineDate').value?new Date($('deadlineDate').value+'T12:00'):null,year=calendarView.getFullYear(),month=calendarView.getMonth(),first=new Date(year,month,1),offset=(first.getDay()+6)%7,last=new Date(year,month+1,0).getDate();$('calendarMonth').textContent=first.toLocaleDateString('nl-NL',{month:'long',year:'numeric'});$('calendarDays').innerHTML='';for(let i=0;i<offset;i++)$('calendarDays').append(document.createElement('span'));for(let day=1;day<=last;day++){const button=document.createElement('button'),iso=`${year}-${String(month+1).padStart(2,'0')}-${String(day).padStart(2,'0')}`;button.type='button';button.textContent=day;button.classList.toggle('selected',selected&&iso===$('deadlineDate').value);button.classList.toggle('today',iso===todayKey());button.onclick=()=>setDeadlineValue(iso,true);$('calendarDays').append(button)}}
function showDeadlineCalendar(){const iso=$('deadlineDate').value;if(iso)calendarView=new Date(iso+'T12:00');$('deadlineCalendar').classList.remove('hidden');renderDeadlineCalendar()}
function setDeadlineValue(iso='',collapse=false){$('deadlineDate').value=iso;$('deadlineDateText').value=iso?formatDateLong(iso):'';if(iso)calendarView=new Date(iso+'T12:00');clearFieldError($('deadlineDateText'));renderDeadlineCalendar();updateActionExtraSummaries();if(collapse&&iso){$('deadlineCalendar').classList.add('hidden');setDisclosure('deadline',false)}}
function normalizeDeadline(collapse=true){const parsed=parseDutchDate($('deadlineDateText').value);if(!parsed){$('deadlineDate').value='';if($('deadlineDateText').value.trim()){clearFieldError($('deadlineDateText'));$('deadlineDateText').classList.add('field-error');if(!$('deadlineDateText').parentElement.querySelector('.field-error-message')){const message=document.createElement('small');message.className='field-error-message smart-date-error';message.textContent='Deze datum klopt niet. Gebruik bijvoorbeeld 02-05-2026.';$('deadlineDateText').parentElement.append(message)}$('deadlineDateText').scrollIntoView({behavior:'smooth',block:'center'});$('deadlineDateText').focus()}return false}setDeadlineValue(parsed.iso,collapse);return true}
function repeatLabel(){return recurrenceLabel({every:+($('repeatEvery').value)||1,unit:$('repeatUnit').value})}
const importanceLabels={1:'Kan wachten',2:'Wil ik graag gedaan hebben',3:'Belangrijk',4:'Kan niet blijven liggen'},resistanceLabels={1:'Nauwelijks',2:'Weinig',3:'Gemiddeld',4:'Veel',5:'Enorm'};
function openTaskDetail(item){$('taskDetailTitle').textContent=item.title;const project=projects.find(entry=>entry.id===item.projectId),projectLabel=$('taskDetailProject'),meta=$('taskDetailMeta');projectLabel.textContent=project?.title||'';projectLabel.classList.toggle('hidden',!project);meta.innerHTML='';const add=(label,value)=>{if(value==null||value==='')return;const row=document.createElement('div'),dt=document.createElement('dt'),dd=document.createElement('dd');dt.textContent=label;dd.textContent=value;row.append(dt,dd);meta.append(row)};add(t('task.load'),item.load?['',t('level.low'),t('level.medium'),t('level.high'),t('level.veryHigh')][item.load]:null);add(t('task.impact'),item.impact?['',t('impact.low'),t('impact.some'),t('impact.much'),t('impact.veryMuch')][item.impact]:null);add(t('task.necessity'),item.necessity?['',t('necessity.wait'),t('necessity.drawback'),t('necessity.must'),t('necessity.problem')][item.necessity]:null);$('taskDetailEditButton').onclick=()=>{close('taskDetailOverlay');openAction(item)};$('taskDetailDeleteButton').onclick=()=>{close('taskDetailOverlay');removeWithUndo(actions,item,saveActions,()=>showScreen(detailOrigin==='projectDetail'?'projectDetail':detailOrigin==='masterlist'?'masterlist':'home'),t('task.deleteConfirm'))};open('taskDetailOverlay')}
function updateResistanceReasonVisibility(){}
function updateActionExtraSummaries(){const project=projects.find(p=>p.id===$('actionProject').value),note=$('actionNote').value.trim(),values={duration:activeActionExtras.has('duration'),deadline:!!$('deadlineDate').value,project:!!project,repeat:activeActionExtras.has('repeat'),note:!!note};$('durationSummary').textContent=values.duration?`Tijdsduur · ${durationLabel($('duration').value).replace('Ongeveer ','')}`:'Kies een tijdsduur';$('deadlineSummary').textContent=values.deadline?`Deadline · ${formatDateLong($('deadlineDate').value)}`:'Moet dit voor een bepaalde datum klaar zijn?';$('projectSummary').textContent=project?`Project · ${project.title}`:'Hoort dit bij een project?';$('repeatSummary').textContent=values.repeat?`Herhalen · ${repeatLabel()}`:'Moet je dit vaker doen?';$('noteSummary').textContent=note?(note.length>58?note.slice(0,58)+'…':note):'Wil je hier nog iets bij onthouden?';document.querySelectorAll('[data-remove-extra]').forEach(b=>b.classList.toggle('hidden',!values[b.dataset.removeExtra]))}
function setTaskContextVisible(visible){$('taskContextSection').classList.toggle('hidden',!visible);$('saveTaskWithContextButton').classList.toggle('hidden',!visible);$('addTaskContextButton').classList.toggle('hidden',visible)}
function openAction(item=null,projectId='',context='general'){editingActionId=item?.id||null;activeTaskContext=item?.context==='household'||item?.type==='household'?'household':context==='household'?'household':'general';formImportance=item?.necessity??null;formImpact=item?.impact??null;formResistance=item?.resistance??null;formLoad=item?.energyDemand??item?.load??null;selectedResistanceReasons=item?.resistanceReasons?.slice()||(item?.resistanceReason?[item.resistanceReason]:[]);activeActionExtras=new Set();if(item?.durationExplicit)activeActionExtras.add('duration');if(item?.repeat?.enabled)activeActionExtras.add('repeat');$('actionTitle').value=item?.title||'';$('duration').value=item?.durationExplicit&&item?.duration?item.duration:'';$('captureEyebrow').textContent=t('capture.taskEyebrow');$('captureTitle').textContent=t('capture.extraTitle');[['impactChoices',formImpact],['resistanceChoices',formResistance],['loadChoices',formLoad]].forEach(([id,value])=>document.querySelectorAll(`#${id} button`).forEach(button=>button.classList.toggle('selected',+button.dataset.value===value)));setDeadlineValue(item?.deadline?.date||'');populateProjects();$('actionProject').value=item?.projectId||projectId;$('repeatEvery').value=item?.repeat?.every||1;$('repeatUnit').value=item?.repeat?.unit||'weeks';$('lastDone').value=item?.repeat?.lastDone||'';$('actionNote').value=item?.note||'';document.querySelectorAll('[data-disclosure]').forEach(button=>setDisclosure(button.dataset.disclosure,false));setTaskContextVisible(!!item);updateActionExtraSummaries();if(typeof prepareActionCapture==='function')prepareActionCapture(item);showScreen('capture');setTimeout(()=>$('actionTitle').focus(),50)}
document.querySelectorAll('#importanceChoices button').forEach(b=>b.onclick=()=>{formImportance=+b.dataset.value;clearChoiceError($('importanceChoices'));document.querySelectorAll('#importanceChoices button').forEach(x=>x.classList.toggle('selected',x===b))});document.querySelectorAll('#resistanceChoices button').forEach(b=>b.onclick=()=>{formResistance=+b.dataset.value;clearChoiceError($('resistanceChoices'));document.querySelectorAll('#resistanceChoices button').forEach(x=>x.classList.toggle('selected',x===b));updateResistanceReasonVisibility()});
document.querySelectorAll('#impactChoices button').forEach(b=>b.onclick=()=>{formImpact=+b.dataset.value;clearChoiceError($('impactChoices'));document.querySelectorAll('#impactChoices button').forEach(x=>x.classList.toggle('selected',x===b))});document.querySelectorAll('#loadChoices button').forEach(b=>b.onclick=()=>{formLoad=+b.dataset.value;clearChoiceError($('loadChoices'));document.querySelectorAll('#loadChoices button').forEach(x=>x.classList.toggle('selected',x===b))});
function renderResistanceReasons(){}
document.querySelectorAll('[data-disclosure]').forEach(b=>{const name=b.dataset.disclosure,remove=document.createElement('button');remove.className='disclosure-remove hidden';remove.type='button';remove.textContent='×';remove.dataset.removeExtra=name;remove.setAttribute('aria-label',({resistanceReason:'Weerstandsreden verwijderen',duration:'Tijdsduur verwijderen',deadline:'Deadline verwijderen',project:'Project verwijderen',repeat:'Herhaling verwijderen',note:'Notitie verwijderen'})[name]);b.after(remove);b.onclick=()=>{const open=b.getAttribute('aria-expanded')!=='true';if(open&&name==='duration'&&!activeActionExtras.has('duration'))$('duration').value='';setDisclosure(name,open);updateActionExtraSummaries()}});
function clearActionExtra(name){if(name==='resistanceReason'){selectedResistanceReasons=[];renderResistanceReasons()}if(name==='duration')activeActionExtras.delete('duration');if(name==='deadline')setDeadlineValue('');if(name==='project')$('actionProject').value='';if(name==='repeat'){activeActionExtras.delete('repeat');$('lastDone').value=''}if(name==='note')$('actionNote').value='';setDisclosure(name,false);updateActionExtraSummaries()}
document.querySelectorAll('[data-remove-extra]').forEach(b=>{b.onclick=e=>{e.stopPropagation();clearActionExtra(b.dataset.removeExtra)};b.onkeydown=e=>{if(e.key==='Enter'||e.key===' '){e.preventDefault();e.stopPropagation();clearActionExtra(b.dataset.removeExtra)}}});
$('duration').onchange=()=>{activeActionExtras.add('duration');updateActionExtraSummaries();setDisclosure('duration',false)};$('deadlineDateText').onfocus=showDeadlineCalendar;$('deadlineDateText').oninput=()=>{const parsed=parseDutchDate($('deadlineDateText').value);if(parsed){$('deadlineDate').value=parsed.iso;calendarView=new Date(parsed.iso+'T12:00');clearFieldError($('deadlineDateText'));renderDeadlineCalendar();updateActionExtraSummaries()}};$('deadlineDateText').onblur=()=>{setTimeout(()=>{if($('deadlineCalendar').contains(document.activeElement))return;const iso=$('deadlineDate').value,text=$('deadlineDateText').value.trim();if(text&&(!iso||text!==formatDateLong(iso)))normalizeDeadline(true)},100)};$('deadlineDateText').onkeydown=e=>{if(e.key==='Enter'){e.preventDefault();normalizeDeadline(true)}if(e.key==='Escape')$('deadlineCalendar').classList.add('hidden')};$('calendarPrev').onclick=()=>{calendarView=new Date(calendarView.getFullYear(),calendarView.getMonth()-1,1);renderDeadlineCalendar()};$('calendarNext').onclick=()=>{calendarView=new Date(calendarView.getFullYear(),calendarView.getMonth()+1,1);renderDeadlineCalendar()};$('actionProject').onchange=()=>{updateActionExtraSummaries();if($('actionProject').value)setDisclosure('project',false)};$('repeatEvery').onchange=()=>{activeActionExtras.add('repeat');updateActionExtraSummaries();setDisclosure('repeat',false)};$('repeatUnit').onchange=()=>{activeActionExtras.add('repeat');updateActionExtraSummaries();setDisclosure('repeat',false)};document.querySelectorAll('[data-repeat]').forEach(button=>button.onclick=()=>{const[every,unit]=button.dataset.repeat.split(',');$('repeatEvery').value=every;$('repeatUnit').value=unit;activeActionExtras.add('repeat');updateActionExtraSummaries();setDisclosure('repeat',false)});$('actionNote').oninput=updateActionExtraSummaries;
$('clearDuration').onclick=()=>clearActionExtra('duration');$('clearRepeat').onclick=()=>clearActionExtra('repeat');
document.addEventListener('pointerdown',e=>{if(currentScreen!=='capture'||e.target.closest('.disclosure-item'))return;document.querySelectorAll('.disclosure-item.open').forEach(item=>setDisclosure(item.querySelector('[data-disclosure]').dataset.disclosure,false));updateActionExtraSummaries()});
$('actionForm').onsubmit=event=>{event.preventDefault();if(!requireField($('actionTitle')))return;const deadlineIso=$('deadlineDate').value,deadlineText=$('deadlineDateText').value.trim();if(deadlineText&&(!deadlineIso||deadlineText!==formatDateLong(deadlineIso))&&!normalizeDeadline(false))return;const existing=editingActionId?actions.find(item=>item.id===editingActionId):null,isNew=!existing,title=$('actionTitle').value.trim(),hasDuration=activeActionExtras.has('duration'),durationValue=$('duration').value,dueDate=$('deadlineDate').value,projectId=$('actionProject').value,note=$('actionNote').value.trim(),hasRepeat=activeActionExtras.has('repeat'),recurrence={enabled:hasRepeat,frequency:legacyFrequency($('repeatUnit').value),interval:+$('repeatEvery').value||1,anchor:existing?.recurrence?.anchor==='completion'?'completion':'calendar',startDate:existing?.recurrence?.startDate||existing?.plannedDate||'',lastCompletedDate:$('lastDone').value,nextDate:existing?.recurrence?.nextDate||''};const data=normalizeTaskModel({...existing,title,context:activeTaskContext,importance:formImportance,necessity:formImportance,impact:formImpact,resistance:formResistance,energyDemand:formLoad,load:formLoad,duration:hasDuration?+durationValue:null,durationExplicit:hasDuration,projectId,note,dueDate,recurrence,type:'task',inference:{source:'user',confidence:null}});if(existing)Object.assign(existing,data);else actions.push(normalizeTaskModel({id:uid(),...data,done:false,lifecycle:{state:TASK_STATES.OPEN,deferredUntil:''},postponeCount:0,completionCount:0,rejectedOn:'',recommendationHistory:{lastRecommended:'',count:0,skips:[]},completionHistory:[],order:actions.length,createdAt:Date.now()}));saveActions();if(typeof clearActionDraft==='function')clearActionDraft();finishInboxConversion();if(isNew)lumiSuccess();showScreen(data.projectId?'projectDetail':'home');if(data.projectId){currentProjectId=data.projectId;renderProjectDetail()}};
$('saveTaskNowButton').onclick=()=>requestActionSave();$('addTaskContextButton').onclick=()=>setTaskContextVisible(true);
function cancelAction(){const changed=!!editingActionId||!!$('actionTitle').value.trim()||!!formImportance||!!formResistance||selectedResistanceReasons.length>0||activeActionExtras.size>0||!!$('deadlineDate').value||!!$('actionProject').value||!!$('actionNote').value.trim(),leave=()=>{pendingInboxConversionId=null;currentProjectId?showProjectDetail(currentProjectId):showScreen(previousScreen==='capture'?'home':previousScreen)};if(!changed)return leave();confirmRemoval(leave,editingActionId?'Weet je zeker dat je je wijzigingen wilt weggooien?':'Weet je zeker dat je wilt annuleren? Wat je hebt ingevuld wordt niet opgeslagen.','Ja, annuleren')}
$('captureBackButton').onclick=cancelAction;
