/* Rollout 3: mobile interaction, calm feedback and user control. */
let todayOrder=read(KEYS.todayOrder,[]),broadenToday=false,captureDraft={};
const saveTodayOrder=()=>write(KEYS.todayOrder,todayOrder);
function todayOrderIndex(item){const index=todayOrder.indexOf(item.id);return index<0?todayOrder.length+item.order:index}
suggestions=function(){const all=actions.filter(item=>!item.done).map(item=>({item,profile:taskRecommendation(item)})).filter(entry=>entry.profile.eligible),best=all.filter(entry=>!entry.profile.lowPriorityHeavy).sort((a,b)=>b.profile.score-a.profile.score)[0]?.profile.score??-999;return all.filter(entry=>!homeSwappedIds.has(entry.item.id)&&(broadenToday||(!entry.profile.lowPriorityHeavy&&entry.profile.score>=best-16))).sort((a,b)=>todayOrderIndex(a.item)-todayOrderIndex(b.item)||b.profile.score-a.profile.score).map(entry=>entry.item)};
function showTodayFeedback(message){const feedback=$('todayFeedback');feedback.textContent=message;feedback.classList.remove('hidden');clearTimeout(window.todayFeedbackTimer);window.todayFeedbackTimer=setTimeout(()=>feedback.classList.add('hidden'),4200)}
function setTodayRecovery(show){$('todayRecoveryActions').classList.toggle('hidden',!show)}
suggestionCard=function(item,secondary=false){const li=document.createElement('li');li.className='suggestion-card';li.dataset.id=item.id;li.tabIndex=0;li.setAttribute('role','group');li.setAttribute('aria-label',`${item.title} bekijken`);const check=checkButton(item,li),project=projects.find(project=>project.id===item.projectId),content=document.createElement('div');content.className='suggestion-content';content.innerHTML=`${project?'<small class="suggestion-project"></small>':''}<div class="suggestion-text"></div><small class="recommendation-why"></small>`;if(project)content.querySelector('.suggestion-project').textContent=project.title;content.querySelector('.suggestion-text').textContent=item.title;content.querySelector('.recommendation-why').textContent=broadenToday&&taskRecommendation(item).load>taskRecommendation(item).available?'Vraagt waarschijnlijk wat meer van je, maar je wilde meer opties zien.':taskRecommendation(item).reason;const swap=document.createElement('button');swap.className='not-today swap-button';swap.innerHTML='<span aria-hidden="true">⇄</span> Wissel';swap.onclick=event=>{event.stopPropagation();const before=suggestions(),replacement=before.length>3||secondary;if(!replacement){showTodayFeedback('Ik zie op dit moment geen andere taak die goed bij je past.');setTodayRecovery(true);return}homeSwappedIds.add(item.id);li.classList.add('leaving');showTodayFeedback('Geen probleem. Ik heb een andere suggestie voor je.');setTimeout(renderHome,240)};li.onclick=event=>{if(!event.target.closest('.check,.swap-button'))openTaskDetail(item)};li.onkeydown=event=>{if((event.key==='Enter'||event.key===' ')&&!event.target.closest('.check,.swap-button')){event.preventDefault();openTaskDetail(item)}};li.append(check,content,swap);wireDrag(li,'today');return li};
renderHome=function(){const all=suggestions(),primary=all.slice(0,3),more=all.slice(3,12),todayCheckin=checkin.date===todayKey()?checkin:null,current=todayCheckin?.energy||null;$('todayDate').textContent=new Intl.DateTimeFormat('nl-NL',{day:'numeric',month:'long',year:'numeric'}).format(new Date());$('todayEnergy').innerHTML=current?`<span class="energy-battery level-${current}" aria-hidden="true"><i></i><i></i><i></i><i></i><i></i></span><b>${current} van 5</b>`:'<b>Nog niet ingecheckt</b>';$('todayEnergy').onclick=openCheckin;const legacyBannerSync=true;$('todayMeaning').textContent=current?`${['','Heel weinig','Weinig','Redelijke','Best veel','Veel'][current]} ruimte vandaag`:'Hoeveel ruimte heb je vandaag?';$('todayAdjustButton').textContent=current?'Aanpassen':'Inchecken';$('todayAdjustButton').onclick=openCheckin;const load=dayLoad();$('todayConsideration').textContent=load?`We houden vandaag rekening met ${load===1?'een lichte afspraak':load===2?'redelijke belasting':'iets zwaars'}.`:'';$('todayConsideration').classList.toggle('hidden',!load);$('suggestionList').innerHTML='';$('moreTodayList').innerHTML='';$('homeCheckinButton').classList.add('hidden');primary.forEach(item=>$('suggestionList').append(suggestionCard(item)));more.forEach(item=>$('moreTodayList').append(suggestionCard(item,true)));$('moreTodayButton').classList.toggle('hidden',!more.length);$('moreTodayList').classList.add('hidden');const noOptions=current&&!primary.length;$('suggestionEmpty').classList.toggle('hidden',!noOptions);if(noOptions){const incomplete=actions.find(item=>!item.done&&(!item.necessity||!item.load));$('suggestionEmpty').innerHTML='';const strong=document.createElement('strong'),small=document.createElement('small');strong.textContent='Voor nu geen passende uitvoeringstaak';small.textContent=incomplete?'Je kunt wel kort context aanvullen voor een betere volgende suggestie.':inbox.length?'Er staat nog iets klaar om later een plek te geven.':'Je hoeft nu niets te forceren.';$('suggestionEmpty').append(strong,small);if(incomplete){const button=document.createElement('button');button.type='button';button.textContent='Context aanvullen';button.onclick=()=>openAction(incomplete);$('suggestionEmpty').append(button)}else if(inbox.length){const button=document.createElement('button');button.type='button';button.textContent='Nog uitzoeken bekijken';button.onclick=()=>showScreen('inbox');$('suggestionEmpty').append(button)}}setTodayRecovery(!!current&&(noOptions||all.length<=1));renderProjectPreview()};
$('broadenSuggestionsButton').onclick=()=>{broadenToday=true;homeSwappedIds.clear();showTodayFeedback('Je ziet nu bewust ook opties die wat meer kunnen vragen.');renderHome()};
$('adjustCheckinButton').onclick=openCheckin;
const recoveredReorder=reorder;
reorder=function(scope,from,to){if(scope!=='today')return recoveredReorder(scope,from,to);const visible=suggestions(),fromIndex=visible.findIndex(item=>item.id===from),toIndex=visible.findIndex(item=>item.id===to);if(fromIndex<0||toIndex<0||fromIndex===toIndex)return;const ids=visible.map(item=>item.id),[moved]=ids.splice(fromIndex,1);ids.splice(toIndex,0,moved);todayOrder=[...ids,...todayOrder.filter(id=>!ids.includes(id)),...actions.map(item=>item.id).filter(id=>!ids.includes(id)&&!todayOrder.includes(id))];saveTodayOrder();renderHome();showTodayFeedback('Volgorde bewaard.')};

function returnToCaptureTypes(){captureDraft.task={title:$('actionTitle').value,importance:formImportance,impact:formImpact,resistance:formResistance,load:formLoad,reasons:selectedResistanceReasons.slice(),duration:$('duration').value};$('universalCaptureText').value=$('actionTitle').value||$('universalCaptureText').value;open('captureTypeOverlay')}
function closeCaptureFlow(){const changed=!!editingActionId||!!$('actionTitle').value.trim()||!!formImportance||!!formImpact||!!formResistance||!!formLoad||selectedResistanceReasons.length>0,leave=()=>{captureDraft={};pendingInboxConversionId=null;close('captureTypeOverlay');currentProjectId?showProjectDetail(currentProjectId):showScreen(previousScreen==='capture'?'home':previousScreen)};if(!changed)return leave();confirmRemoval(leave,editingActionId?'Weet je zeker dat je je wijzigingen wilt weggooien?':'Wil je de capture sluiten? Je invoer wordt dan niet opgeslagen.','Ja, sluiten')}
$('captureBackButton').onclick=returnToCaptureTypes;
$('captureCloseButton').onclick=closeCaptureFlow;
$('cancelActionButton').onclick=closeCaptureFlow;
$('captureTypeOverlay').querySelector('.modal-close').onclick=()=>{if(currentScreen==='capture')closeCaptureFlow();else close('captureTypeOverlay')};
const recoveredOpenCapturedType=openCapturedType;
openCapturedType=function(type){if(type!=='task'){if(currentScreen==='capture')showScreen(previousScreen==='capture'?'home':previousScreen);return recoveredOpenCapturedType(type)}close('captureTypeOverlay');if(currentScreen!=='capture')openAction();const draft=captureDraft.task;if(draft){$('actionTitle').value=draft.title||$('universalCaptureText').value;formImportance=draft.importance;formImpact=draft.impact;formResistance=draft.resistance;formLoad=draft.load;selectedResistanceReasons=draft.reasons||[];$('duration').value=draft.duration||'';renderResistanceReasons();[['importanceChoices',formImportance],['impactChoices',formImpact],['resistanceChoices',formResistance],['loadChoices',formLoad]].forEach(([id,value])=>document.querySelectorAll(`#${id} button`).forEach(button=>button.classList.toggle('selected',+button.dataset.value===value)))}else $('actionTitle').value=$('universalCaptureText').value.trim()};
document.querySelectorAll('[data-capture-type]').forEach(button=>button.onclick=()=>openCapturedType(button.dataset.captureType));

$('actionForm').onsubmit=event=>{event.preventDefault();const titleOk=requireField($('actionTitle')),necessityOk=requireChoice($('importanceChoices'),formImportance),impactOk=requireChoice($('impactChoices'),formImpact),resistanceOk=requireChoice($('resistanceChoices'),formResistance),loadOk=requireChoice($('loadChoices'),formLoad);if(!titleOk||!necessityOk||!impactOk||!resistanceOk||!loadOk)return;const deadlineIso=$('deadlineDate').value,deadlineText=$('deadlineDateText').value.trim();if(deadlineText&&(!deadlineIso||deadlineText!==formatDateLong(deadlineIso))&&!normalizeDeadline(false))return;const title=$('actionTitle').value.trim(),hasDuration=activeActionExtras.has('duration')&&!!$('duration').value,projectId=$('actionProject').value,hasRepeat=activeActionExtras.has('repeat'),data={title,importance:formImportance??null,necessity:formImportance??null,impact:formImpact??null,resistance:formResistance??null,load:formLoad??null,resistanceReason:'',resistanceReasons:selectedResistanceReasons.slice(),duration:hasDuration?+$('duration').value:null,durationExplicit:hasDuration,projectId,note:$('actionNote').value.trim(),deadline:{enabled:!!deadlineIso,date:deadlineIso},repeat:{enabled:hasRepeat,every:+$('repeatEvery').value||1,unit:$('repeatUnit').value,lastDone:$('lastDone').value,nextDue:''},type:'task',inference:{source:'user',confidence:null}};if(editingActionId)Object.assign(actions.find(item=>item.id===editingActionId),data);else actions.push({id:uid(),...data,lifecycle:{state:'open',deferredUntil:''},done:false,postponeCount:0,completionCount:0,rejectedOn:'',recommendationHistory:{lastRecommended:'',count:0,skips:[]},completionHistory:[],order:actions.length,createdAt:Date.now()});saveActions();finishInboxConversion();captureDraft={};lumiSuccess();showScreen(data.projectId?'projectDetail':'home');if(data.projectId){currentProjectId=data.projectId;renderProjectDetail()}};

const durationGrid=document.createElement('div');durationGrid.className='duration-choice-grid';Array.from($('duration').options).filter(option=>option.value).forEach(option=>{const button=document.createElement('button');button.type='button';button.dataset.duration=option.value;button.textContent=option.textContent;button.onclick=()=>{$('duration').value=option.value;activeActionExtras.add('duration');durationGrid.querySelectorAll('button').forEach(other=>other.classList.toggle('selected',other===button));updateActionExtraSummaries();setDisclosure('duration',false)};durationGrid.append(button)});$('duration').classList.add('duration-native-fallback');$('duration').after(durationGrid);
const recoveredOpenAction=openAction;openAction=function(item=null,projectId=''){recoveredOpenAction(item,projectId);durationGrid.querySelectorAll('button').forEach(button=>button.classList.toggle('selected',button.dataset.duration===$('duration').value))};

function updateResistanceHelp(){const button=$('resistanceHelpButton'),reason=selectedResistanceReasons.find(value=>/groot|beginnen|stappen|uitzoeken|beslissen|contact|lukt/.test(value));button.classList.toggle('hidden',!reason);button.textContent=/contact/.test(reason)?'Hulp bij de eerste contactstap':/uitzoeken|beslissen/.test(reason)?'Maak de uitzoekvraag concreet':'Help me deze taak kleiner te maken'}
const recoveredRenderResistanceReasons=renderResistanceReasons;renderResistanceReasons=function(){recoveredRenderResistanceReasons();updateResistanceHelp()};
$('resistanceHelpButton').onclick=()=>{setDisclosure('note',true);if(!$('actionNote').value.trim())$('actionNote').value=selectedResistanceReasons.some(reason=>/contact/.test(reason))?'Eerste contactstap: ':selectedResistanceReasons.some(reason=>/uitzoeken|beslissen/.test(reason))?'Eerst uitzoeken: ':'Eerste kleine stap: ';updateActionExtraSummaries();$('actionNote').focus();showTodayFeedback('Noteer alleen de eerstvolgende kleine stap.')};

document.querySelector('#wishlistOverlay .field-label[for="wishlistName"]').textContent='Wat wil je aanschaffen of laten doen?';
$('wishlistName').placeholder='Bijv. lamp, tattoo of workshop';
$('saveWishlistButton').textContent='Bewaren';
const recoveredOpenWishlistR3=openWishlist;openWishlist=function(item=null){recoveredOpenWishlistR3(item);$('wishlistModalTitle').textContent=item?'Wens of aankoop bewerken':'Nieuwe wens of aankoop'};
document.querySelector('.purchase-tools').classList.add('manual-order-primary');
// Positieve acties krijgen stille Lumi-feedback; herstelgevoelig verwijderen houdt de teksttoast met Ongedaan maken.

