/** Today recommendation selection, rendering, swapping and ordering. */
let todayOrder=read(KEYS.todayOrder,[]),broadenToday=false,captureDraft={};
const saveTodayOrder=()=>write(KEYS.todayOrder,todayOrder);
function todayOrderIndex(item){const index=todayOrder.indexOf(item.id);return index<0?todayOrder.length+item.order:index}
function taskRecommendation(item){return recommendationEngine.profile(item,{checkin,dayLoad:0})}
function recommendationSets(){return recommendationEngine.sets(actions,{checkin,dayLoad:0,swappedIds:homeSwappedIds,orderIndex:todayOrderIndex,broaden:broadenToday})}
function suggestions(){return recommendationSets().visible.map(entry=>entry.item)}
function showTodayFeedback(message){const feedback=$('todayFeedback');feedback.textContent=message;feedback.classList.remove('hidden');clearTimeout(window.todayFeedbackTimer);window.todayFeedbackTimer=setTimeout(()=>feedback.classList.add('hidden'),4200)}
function setTodayRecovery(show){$('todayRecoveryActions').classList.toggle('hidden',!show)}
function suggestionCard(item,secondary=false){const li=document.createElement('li');li.className='suggestion-card';li.dataset.id=item.id;li.tabIndex=0;li.setAttribute('role','group');li.setAttribute('aria-label',t('today.viewTask',{title:item.title}));const check=checkButton(item,li),project=projects.find(entry=>entry.id===item.projectId),content=document.createElement('div');content.className='suggestion-content';content.innerHTML=`${project?'<small class="suggestion-project"></small>':''}<div class="suggestion-text"></div><small class="recommendation-why"></small>`;if(project)content.querySelector('.suggestion-project').textContent=displayProjectName(project.title);content.querySelector('.suggestion-text').textContent=item.title;content.querySelector('.recommendation-why').textContent=taskRecommendation(item).reason;const swap=document.createElement('button');swap.className='not-today swap-button';swap.innerHTML=`<span aria-hidden="true">⇄</span> ${t('today.swap')}`;swap.onclick=event=>{event.stopPropagation();if(!(suggestions().length>3||secondary)){showTodayFeedback(t('today.noAlternative'));setTodayRecovery(true);return}homeSwappedIds.add(item.id);li.classList.add('leaving');showTodayFeedback(t('today.swapped'));setTimeout(renderHome,240)};li.onclick=event=>{if(!event.target.closest('.check,.swap-button'))openTaskDetail(item)};li.onkeydown=event=>{if((event.key==='Enter'||event.key===' ')&&!event.target.closest('.check,.swap-button')){event.preventDefault();openTaskDetail(item)}};li.append(check,content,swap);wireDrag(li,'today');return li}
function renderHome(){renderHomeScreen({$,sets:recommendationSets(),checkin,todayKey,suggestionCard,openCheckin,renderProjectPreview,broaden:broadenToday});if(typeof addUrgentPurchaseToHome==='function')addUrgentPurchaseToHome();document.querySelector('.projects-preview')?.classList.add('hidden')}
$('broadenSuggestionsButton').onclick=()=>{const before=recommendationSets().visible.length;if(!recommendationSets().extra.length)return renderHome();broadenToday=true;homeSwappedIds.clear();renderHome();if(recommendationSets().visible.length>before)showTodayFeedback(t('today.broadened'))};$('adjustCheckinButton').onclick=()=>openCheckin();
