const test=require('node:test'),assert=require('node:assert/strict'),fs=require('node:fs'),vm=require('node:vm'),path=require('node:path');
const context=vm.createContext({Date,console,t:key=>key});
for(const file of ['js/utils/dates.js','js/core/task-model.js'])vm.runInContext(fs.readFileSync(path.join(__dirname,'..',file),'utf8'),context,{filename:file});
const run=source=>vm.runInContext(source,context);

test('quarterly occurrence advances from actual completion date',()=>{const result=run(`completeTaskOccurrence({title:'Kattenbakken geheel verschonen',repeat:{enabled:true,every:3,unit:'months'},completionCount:0,completionHistory:[]},{completedDate:'2026-09-07'})`);assert.equal(result.recurrence.lastCompletedDate,'2026-09-07');assert.equal(result.recurrence.nextDate,'2026-12-07');assert.equal(result.repeat.lastDone,'2026-09-07');assert.equal(result.repeat.nextDue,'2026-12-07');assert.equal(result.done,false);assert.deepEqual(Array.from(result.completionHistory),['2026-09-07']);assert.equal(run(`getTaskRelevance(${JSON.stringify(result)},{today:'2026-09-07'}).actionable`),false)});
for(const[name,every,unit,completed,expected]of[['daily',1,'days','2026-09-07','2026-09-08'],['weekly',1,'weeks','2026-09-07','2026-09-14'],['monthly at month end',1,'months','2026-01-31','2026-02-28']])test(`${name} recurrence has one next occurrence`,()=>{const result=run(`completeTaskOccurrence({repeat:{enabled:true,every:${every},unit:'${unit}'},completionCount:0,completionHistory:[]},{completedDate:'${completed}'})`);assert.equal(result.recurrence.nextDate,expected);assert.equal(result.completionCount,1);assert.equal(result.completionHistory.length,1)});
test('ordinary task keeps normal completion semantics',()=>{const result=run(`completeTaskOccurrence({title:'Losse taak',completionCount:0,completionHistory:[]},{completedDate:'2026-09-07'})`);assert.equal(result.done,true);assert.equal(result.lifecycle.state,'completed')});
test('future household routine stays hidden until due',()=>{const task=`{repeat:{enabled:true,every:1,unit:'weeks',lastDone:'2026-09-07',nextDue:'2026-09-14'}}`;assert.equal(run(`getTaskRelevance(${task},{today:'2026-09-08'}).actionable`),false);assert.equal(run(`getTaskRelevance(${task},{today:'2026-09-14'}).actionable`),true)});
