window.LUMI_LOCALES=window.LUMI_LOCALES||{};
window.LUMI_LOCALES.en={
  'task.load':'Demand','task.impact':'Benefit','task.necessity':'Necessity','task.deleteConfirm':'Are you sure you want to delete this task?','level.low':'Low','level.medium':'Moderate','level.high':'High','level.veryHigh':'Very high','necessity.wait':'Can wait','necessity.drawback':'Delay has drawbacks','necessity.must':'Must be done','necessity.problem':'Delay causes problems',
  'status.open':'Open','status.waiting':'Waiting for','status.later':'Later','status.done':'Done',
  'waiting.forPrompt':'Who or what are you waiting for? (optional)','waiting.followUpPrompt':'When should this return? Enter YYYY-MM-DD or leave blank.','waiting.since':'Waiting since {date}','waiting.noResponse':'No response from {name} yet','waiting.generic':'Waiting for follow-up','waiting.keep':'Keep waiting','waiting.followUp':'Follow up','waiting.set':'Waiting for',
  'later.set':'Later','later.prompt':'When should this return? Enter YYYY-MM-DD or leave blank for no date.','later.noDate':'No date','later.resurfaced':'Resurfaced','later.resurface':'Resurface',
  'date.planned':'Planned','date.deadline':'Deadline','date.resurface':'Resurface','date.invalid':'Use a valid date in the form YYYY-MM-DD.',
  'recurrence.afterCompletion':'After completion','recurrence.daily':'Daily','recurrence.weekly':'Weekly','recurrence.monthly':'Monthly','recurrence.quarterly':'Quarterly','recurrence.halfYearly':'Every six months','recurrence.yearly':'Yearly','recurrence.every':'Every {interval} {unit}','recurrence.day.one':'day','recurrence.day.many':'days','recurrence.week.one':'week','recurrence.week.many':'weeks','recurrence.month.one':'month','recurrence.month.many':'months','recurrence.year.one':'year','recurrence.year.many':'years',
  'reason.energyFit':'Fits your energy','reason.lowEnergy':'Low energy','reason.deadline':'Deadline approaching','reason.important':'Important soon','reason.lowResistance':'Low resistance','reason.resurfaced':'Relevant again','reason.duration':'± {minutes} min','reason.contextUnknown':'Not enough context yet to judge the fit',
  'menu.edit':'Edit','menu.delete':'Delete','menu.cancel':'Cancel',
  'capture.saveNow':'Save now','capture.addContext':'Add context','capture.saveTask':'Save in my Vault','context.title':'Extra context','context.help':'Everything below is optional.','task.energyQuestion':'How much energy does this take while you are doing it?','task.resistanceQuestion':'How much do you dread getting started?','task.impactQuestion':'What will it give you when it is done?','impact.low':'A little','impact.some':'Some','impact.much':'A lot','impact.veryMuch':'A great deal','resurface.question':'When do you want to think about this again?',
  'purchase.typeQuestion':'Do you need it or is it a wish?','purchase.timingQuestion':'When do you need it / can it wait?','purchase.extraTitle':'Extra information','purchase.price':'Price','purchase.addPrice':'Add a price','purchase.link':'Link','purchase.addLink':'Add a link','purchase.photo':'Photo','purchase.addPhoto':'Add a photo','purchase.date':'Before a certain date','purchase.addDate':'Add a date','purchase.color':'Color (optional)','purchase.need':'Need','purchase.wish':'Wish','purchase.wishlist':'Wishlist','purchase.canWait':'Can wait','purchase.soon':'Soon','purchase.now':'Need now','purchase.emptyDone':'Nothing purchased yet','purchase.emptyNeed':'Nothing needed yet','purchase.emptyWish':'No wishes yet','purchase.empty':'No purchases yet','purchase.edit':'Edit purchase','purchase.new':'New purchase','purchase.photoKept':'Photo saved','purchase.wishTiming':'When would you like this?','purchase.needTiming':'When do you need it?','purchase.noRush':'No rush','purchase.byDate':'Before a certain date','purchase.search':'Search purchases','purchase.all':'All','purchase.done':'Done',
  'project.edit':'Edit project','project.new':'New project','project.icon':'Icon','project.active':'Active','project.completed':'Completed','project.archive':'Mark completed','project.reopen':'Make active again','nav.projects':'Projects',
  'bucket.defaults.2026':'2026','bucket.defaults.2027':'2027','bucket.defaults.someday':'Someday','bucket.empty':'Nothing added yet.','bucket.addItem':'+ Add item','bucket.addList':'+ Add list','bucket.listName':'Name of the new bucket list','bucket.rename':'Rename','bucket.color':'Choose color','bucket.delete':'Delete','bucket.itemPrompt':'Add to {name}','bucket.itemEdit':'Bucket list item',
  'energy.eyebrow':'Your energy','energy.question':'How much capacity do you have right now?','energy.help':'Choose what comes closest.','energy.homeQuestion':'How is your energy?','energy.homeHelp':'Indicate how much capacity you have.','energy.currentTitle':'Your energy','energy.notSet':'Not set yet','energy.set':'Set energy','energy.change':'Change energy','energy.settingsCurrent':'Current energy: level {level}','energy.settingsHelp':'View and change your energy','energy.level.1':'Very little','energy.level.2':'Low','energy.level.3':'Moderate','energy.level.4':'Quite a lot','energy.level.5':'High','energy.status.1':'Very little energy','energy.status.2':'Low energy','energy.status.3':'Moderate energy','energy.status.4':'Quite a lot of energy','energy.status.5':'High energy','energy.save':'Save energy',
  'today.viewTask':'View {title}','today.swap':'Swap task','today.noAlternative':'I cannot find another task that fits right now.','today.swapped':'No problem. I found another suggestion.','today.broadened':'You are now also seeing options that may take more energy.','today.broaden':'Also show heavier options','today.broadenHelp':'Also show tasks that may take more energy.','today.orderSaved':'Order saved.','today.emptyTitle':'No suitable tasks right now','today.emptyHelp':'You do not need to force anything right now.',
  'task.completed':'Completed ✓','undo':'Undo','masterlist.noResults':'No tasks found','masterlist.adjustSearch':'Adjust your search','masterlist.emptyDone':'Nothing completed yet','masterlist.emptyDoneHelp':'Completed tasks appear here','masterlist.emptyWaiting':'Nothing is waiting','masterlist.emptyWaitingHelp':'Tasks that depend on someone or something appear here','masterlist.emptyLater':'Nothing for later','masterlist.emptyLaterHelp':'Deferred tasks appear here','masterlist.emptyOpen':'No tasks yet','masterlist.emptyOpenHelp':'Add a task',
  'capture.closeConfirm':'Close capture? Your input remains saved as a draft.','capture.close':'Close','capture.saveChanges':'Save changes','capture.deleteDraftConfirm':'Delete this draft?','capture.deleteDraft':'Delete draft','capture.purchase':'Purchase / wish','capture.household':'Household task','capture.bucketItem':'Bucket-list item','capture.taskEyebrow':'Task','capture.extraTitle':'Extra information','capture.householdSaved':'Household task','capture.bucketSaved':'Bucket-list item',
  'vault.searchEmpty':'No results found','vault.searchType.task':'Masterlist','vault.searchType.purchase':'Purchases','vault.searchType.idea':'Ideas','vault.searchType.list':'Lists','vault.searchType.bucket':'Bucket list','vault.searchType.project':'Projects','vault.searchType.household':'Household','vault.projects':'Projects',
  'color.purple':'Purple','color.pink':'Pink','color.blue':'Blue','color.teal':'Teal','color.green':'Green','color.gold':'Gold','color.rose':'Red'
};
