window.LUMI_LOCALES=window.LUMI_LOCALES||{};
window.LUMI_LOCALES.nl={
  'task.load':'Belasting','task.impact':'Opbrengst','task.necessity':'Noodzaak','task.deleteConfirm':'Weet je zeker dat je deze taak wilt verwijderen?','level.low':'Weinig','level.medium':'Redelijk','level.high':'Veel','level.veryHigh':'Heel veel','necessity.wait':'Kan rustig wachten','necessity.drawback':'Uitstel geeft nadelen','necessity.must':'Moet echt gebeuren','necessity.problem':'Uitstel veroorzaakt problemen',
  'status.open':'Open','status.waiting':'Wachten op','status.later':'Later','status.done':'Gedaan',
  'waiting.forPrompt':'Waar/wie wacht je op? (optioneel)','waiting.followUpPrompt':'Wanneer wil je dit weer zien? Vul een datum in als JJJJ-MM-DD, of laat leeg.','waiting.since':'Wacht sinds {date}','waiting.noResponse':'Nog geen reactie van {name}','waiting.generic':'Wachten op opvolging','waiting.keep':'Nog wachten','waiting.followUp':'Opvolgen','waiting.set':'Wachten op',
  'later.set':'Later','later.prompt':'Wanneer wil je dit weer zien? Vul een datum in als JJJJ-MM-DD, of laat leeg voor geen datum.','later.noDate':'Geen datum','later.resurfaced':'Teruggebracht','later.resurface':'Terugbrengen',
  'date.planned':'Gepland','date.deadline':'Deadline','date.resurface':'Terugbrengen','date.invalid':'Gebruik een geldige datum in de vorm JJJJ-MM-DD.',
  'recurrence.afterCompletion':'Na voltooiing','recurrence.daily':'Dagelijks','recurrence.weekly':'Wekelijks','recurrence.monthly':'Maandelijks','recurrence.quarterly':'Per kwartaal','recurrence.halfYearly':'Halfjaarlijks','recurrence.yearly':'Jaarlijks','recurrence.every':'Iedere {interval} {unit}','recurrence.day.one':'dag','recurrence.day.many':'dagen','recurrence.week.one':'week','recurrence.week.many':'weken','recurrence.month.one':'maand','recurrence.month.many':'maanden','recurrence.year.one':'jaar','recurrence.year.many':'jaar',
  'reason.energyFit':'Past bij je energie','reason.lowEnergy':'Weinig energie','reason.deadline':'Deadline nadert','reason.important':'Binnenkort belangrijk','reason.lowResistance':'Weinig weerstand','reason.resurfaced':'Opnieuw relevant','reason.duration':'± {minutes} min',
  'menu.edit':'Bewerken','menu.delete':'Verwijderen','menu.cancel':'Annuleren',
  'capture.saveNow':'Nu bewaren','capture.addContext':'Context toevoegen','capture.saveTask':'Bewaar in mijn Vault','context.title':'Extra context','context.help':'Alles hieronder is optioneel.','task.energyQuestion':'Hoeveel vraagt het van je als je ermee bezig bent?','task.resistanceQuestion':'Hoe erg zie je ertegenop om eraan te beginnen?','task.impactQuestion':'Wat levert het op als het gedaan is?','impact.low':'Weinig','impact.some':'Een beetje','impact.much':'Veel','impact.veryMuch':'Heel veel','resurface.question':'Wanneer wil je hier weer aan denken?',
  'purchase.typeQuestion':'Heb je het nodig of is het een wens?','purchase.timingQuestion':'Wanneer heb je het nodig / kan het wachten?','purchase.extraTitle':'Extra informatie','purchase.price':'Prijs','purchase.addPrice':'Voeg een prijs toe','purchase.link':'Link','purchase.addLink':'Voeg een link toe','purchase.photo':'Foto','purchase.addPhoto':'Voeg een foto toe','purchase.date':'Voor een bepaalde datum','purchase.addDate':'Voeg datum toe','purchase.color':'Kleur (optioneel)','purchase.need':'Nodig','purchase.wish':'Wens','purchase.wishlist':'Wishlist','purchase.canWait':'Kan wachten','purchase.soon':'Binnenkort','purchase.now':'Nu nodig','purchase.emptyDone':'Nog niets gekocht','purchase.emptyNeed':'Nog niets nodig','purchase.emptyWish':'Nog geen wensen','purchase.empty':'Nog geen aankopen','purchase.edit':'Aankoop bewerken','purchase.new':'Nieuwe aankoop','purchase.photoKept':'Foto bewaard','purchase.wishTiming':'Wanneer wil je dit?','purchase.needTiming':'Wanneer heb je het nodig?','purchase.noRush':'Geen haast','purchase.byDate':'Voor een bepaalde datum','purchase.search':'Zoek in Kopen','purchase.all':'Alles','purchase.done':'Geregeld',
  'project.edit':'Project bewerken','project.new':'Nieuw project','project.icon':'Icoon','project.active':'Actief','project.completed':'Afgerond','project.archive':'Markeer als afgerond','project.reopen':'Maak weer actief','nav.projects':'Projecten',
  'bucket.defaults.2026':'2026','bucket.defaults.2027':'2027','bucket.defaults.someday':'Ooit','bucket.empty':'Nog niets toegevoegd.','bucket.addItem':'+ Item toevoegen','bucket.addList':'+ Lijst toevoegen','bucket.listName':'Naam van de nieuwe bucketlist','bucket.rename':'Hernoemen','bucket.color':'Kleur kiezen','bucket.delete':'Verwijderen','bucket.itemPrompt':'Toevoegen aan {name}','bucket.itemEdit':'Bucketlist-item',
  'energy.eyebrow':'Jouw energie','energy.question':'Hoeveel ruimte heb je nu?','energy.help':'Kies wat het dichtst in de buurt komt.','energy.homeQuestion':'Hoe is je energie?','energy.homeHelp':'Geef aan hoeveel ruimte je hebt.','energy.currentTitle':'Jouw energie','energy.notSet':'Nog niet ingevuld','energy.set':'Energie aangeven','energy.change':'Energie wijzigen','energy.settingsCurrent':'Huidige energie: niveau {level}','energy.settingsHelp':'Bekijk en pas je energie aan','energy.level.1':'Heel weinig','energy.level.2':'Weinig','energy.level.3':'Redelijk','energy.level.4':'Best veel','energy.level.5':'Veel','energy.status.1':'Heel weinig energie','energy.status.2':'Weinig energie','energy.status.3':'Redelijke energie','energy.status.4':'Best veel energie','energy.status.5':'Veel energie','energy.save':'Energie bewaren',
  'today.viewTask':'{title} bekijken','today.swap':'Wissel taak','today.noAlternative':'Ik zie op dit moment geen andere taak die goed bij je past.','today.swapped':'Geen probleem. Ik heb een andere suggestie voor je.','today.broadened':'Je ziet nu bewust ook opties die wat meer kunnen vragen.','today.broaden':'Ook zwaardere opties bekijken','today.broadenHelp':'Ook taken bekijken die wat meer van je vragen.','today.orderSaved':'Volgorde bewaard.','today.emptyTitle':'Geen passende taken voor nu','today.emptyHelp':'Je hoeft nu niets te forceren.',
  'task.completed':'Afgerond ✓','undo':'Ongedaan maken','masterlist.noResults':'Geen taken gevonden','masterlist.adjustSearch':'Pas je zoekopdracht aan','masterlist.emptyDone':'Nog niets afgerond','masterlist.emptyDoneHelp':'Afgeronde taken verschijnen hier','masterlist.emptyWaiting':'Niets staat te wachten','masterlist.emptyWaitingHelp':'Taken die van iets of iemand anders afhangen verschijnen hier','masterlist.emptyLater':'Niets voor later','masterlist.emptyLaterHelp':'Uitgestelde taken verschijnen hier','masterlist.emptyOpen':'Nog geen taken','masterlist.emptyOpenHelp':'Voeg een taak toe',
  'capture.closeConfirm':'Wil je de capture sluiten? Je invoer blijft als concept bewaard.','capture.close':'Sluiten','capture.saveChanges':'Wijzigingen opslaan','capture.deleteDraftConfirm':'Wil je dit concept verwijderen?','capture.deleteDraft':'Concept verwijderen','capture.purchase':'Aankoop / wens','capture.household':'Huishoudelijke taak','capture.bucketItem':'Bucketlist-item','capture.taskEyebrow':'Taak','capture.extraTitle':'Extra informatie','capture.householdSaved':'Huishoudelijke taak','capture.bucketSaved':'Bucketlist-item',
  'vault.searchEmpty':'Geen resultaten gevonden','vault.searchType.task':'Masterlist','vault.searchType.purchase':'Kopen','vault.searchType.idea':'Ideeën','vault.searchType.list':'Lijstjes','vault.searchType.bucket':'Bucketlist','vault.searchType.project':'Projecten','vault.searchType.household':'Huishouden','vault.projects':'Projecten',
  'color.purple':'Paars','color.pink':'Roze','color.blue':'Blauw','color.teal':'Turquoise','color.green':'Groen','color.gold':'Goud','color.rose':'Rood'
};
